import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'ta' | 'hi' | 'te' | 'es';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.farmDetails': 'Farm Details',
    'nav.cropSuggestion': 'Crop Suggestion',
    'nav.fertilizer': 'Fertilizer',
    'nav.weather': 'Weather',
    'nav.diseases': 'Diseases',
    'nav.gallery': 'Image Gallery',
    'nav.marketPrices': 'Market Prices',
    'nav.aiAssistant': 'Smart Assistant',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.adminTools': 'Admin Tools',
    'nav.contactUs': 'Contact Us',
    'nav.about': 'About Us',
    'nav.needHelp': 'Need Help?',
    'nav.helpSubtitle': 'Contact our support team for assistance',
    'nav.home': 'Home',
    'nav.login': 'Sign In',
    'nav.register': 'Get Started',

    // Header & User Menu
    'header.notifications': 'Notifications',
    'header.markRead': 'Mark all as read',
    'header.signOut': 'Sign Out',
    'header.myProfile': 'My Profile',
    'header.settings': 'Settings',
    'header.new': 'new',
    'header.noNotifications': 'No new notifications',

    // Common Buttons & Labels
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.search': 'Search...',
    'common.select': 'Select Language',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.viewAll': 'View All',
    'common.details': 'Details',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.action': 'Action',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.viewDetails': 'View Details',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.showing': 'Showing',
    'common.to': 'to',
    'common.of': 'of',
    'common.items': 'items',
    'common.all': 'All',
    'common.clear': 'Clear',
    'common.clearChat': 'Clear Chat',
    'common.copied': 'Copied to clipboard',
    'common.success': 'Success',
    'common.error': 'Error occurred',
    'common.perQuintal': 'per quintal',
    'common.acres': 'acres',

    // Dashboard
    'dash.welcome': 'Welcome',
    'dash.subtitle': "Here's what's happening with your farm today",
    'dash.statCrops': 'Total Crops',
    'dash.statRecs': 'My Crop Suggestions',
    'dash.statMarket': 'Market Prices',
    'dash.statFarmers': 'Farmers Using App',
    'dash.weatherTitle': 'Weather Forecast',
    'dash.humidity': 'Humidity',
    'dash.wind': 'Wind Speed',
    'dash.chartWeather': 'Weather for Next 7 Days',
    'dash.chartSeasons': 'Crops by Season',
    'dash.chartYield': 'Expected Monthly Harvest',
    'dash.recentRecs': 'Recent Crop Suggestions',
    'dash.noRecs': 'No crop suggestions yet. Try getting your first suggestion!',
    'dash.getRecBtn': 'Get Crop Suggestions',
    'dash.match': 'match',
    'dash.quickActions': 'Quick Actions',

    // Crop Recommendation
    'crop.title': 'Crop Recommendation',
    'crop.subtitle': 'Get smart crop suggestions tailored to your soil & climate',
    'crop.nitrogen': 'Nitrogen (N)',
    'crop.phosphorus': 'Phosphorus (P)',
    'crop.potassium': 'Potassium (K)',
    'crop.ph': 'pH Level',
    'crop.rainfall': 'Rainfall (mm)',
    'crop.temperature': 'Temperature (°C)',
    'crop.humidity': 'Humidity (%)',
    'crop.soilType': 'Soil Type',
    'crop.season': 'Season',
    'crop.getRecommendation': 'Get Recommendation',
    'crop.results': 'Recommended Crops',
    'crop.confidence': 'Suitability Score',
    'crop.duration': 'Growth Duration',
    'crop.waterReq': 'Water Requirement',
    'crop.yield': 'Expected Yield',
    'crop.marketValue': 'Market Value',
    'crop.scientificName': 'Scientific Name',
    'crop.fertilizerPlan': 'Fertilizer Plan',

    // Fertilizer
    'fertilizer.title': 'Fertilizer Advisory',
    'fertilizer.subtitle': 'Calculate precise fertilizer dosage for optimal yield',
    'fertilizer.crop': 'Select Crop',
    'fertilizer.area': 'Land Area (Acres)',
    'fertilizer.currentN': 'Current Nitrogen (kg/acre)',
    'fertilizer.currentP': 'Current Phosphorus (kg/acre)',
    'fertilizer.currentK': 'Current Potassium (kg/acre)',
    'fertilizer.calculate': 'Calculate Dosage',
    'fertilizer.result': 'Recommended Fertilizers',
    'fertilizer.urea': 'Urea (46% N)',
    'fertilizer.dap': 'DAP (Di-ammonium Phosphate)',
    'fertilizer.mop': 'MOP (Muriate of Potash)',
    'fertilizer.organic': 'Organic Alternatives',
    'fertilizer.schedule': 'Application Schedule',
    'fertilizer.precautions': 'Precautions & Safety',

    // Weather
    'weather.title': 'Weather Advisory',
    'weather.subtitle': 'Hyper-local weather forecasts and farming alerts',
    'weather.searchLoc': 'Search location or district...',
    'weather.useMyLocation': 'Use Current Location',
    'weather.tempMax': 'Highest Temp',
    'weather.tempMin': 'Lowest Temp',
    'weather.rainProb': 'Precipitation Chance',
    'weather.farmingTip': 'Farming Advisory',
    'weather.rainAlert': 'Rainfall expected! Postpone spraying pesticides and harvesting.',
    'weather.uvIndex': 'UV Index',
    'weather.pressure': 'Pressure',
    'weather.visibility': 'Visibility',
    'weather.sunrise': 'Sunrise',
    'weather.sunset': 'Sunset',
    'weather.hourlyForecast': 'Hourly Forecast',
    'weather.weeklyForecast': '7-Day Forecast',

    // Diseases
    'diseases.title': 'Pest & Disease Identification',
    'diseases.subtitle': 'Identify crop diseases and get organic & chemical treatments',
    'diseases.inspectBtn': 'Inspect Crop Image',
    'diseases.uploadImg': 'Upload Crop Photo',
    'diseases.analyzing': 'Analyzing crop health...',
    'diseases.examiningLeaves': 'Our AI is examining the leaves for pathogens...',
    'diseases.diagnosisTitle': 'AI Diagnosis Report',
    'diseases.symptoms': 'Symptoms to Look For',
    'diseases.causes': 'Primary Causes',
    'diseases.prevention': 'Prevention Steps',
    'diseases.treatment': 'Treatment & Control',
    'diseases.chemical': 'Chemical Treatment',
    'diseases.organic': 'Organic Solution',
    'diseases.viewGuide': 'View Treatment Guide',
    'diseases.emptyTitle': 'No Matching Diseases Found',
    'diseases.emptyMsg': 'Try searching for crops like Paddy, Tomato, Wheat, Banana, Cotton...',

    // Market Prices
    'market.title': 'Market Prices & Trends',
    'market.subtitle': 'Live mandi prices and market rate analysis',
    'market.topGainer': 'Top Gainer Today',
    'market.avgRate': 'Average Mandi Rate',
    'market.activeMandis': 'Active Mandis',
    'market.sentiment': 'Market Sentiment',
    'market.commodity': 'Commodity',
    'market.marketName': 'Market / Mandi',
    'market.minPrice': 'Min Price',
    'market.maxPrice': 'Max Price',
    'market.modalPrice': 'Modal Price',
    'market.prevPrice': 'Previous Price',
    'market.trend24h': '24h Trend',
    'market.district': 'District',
    'market.filterCrop': 'Filter by Crop',
    'market.allMandis': 'All Mandis / Markets',
    'market.bullish': 'Bullish',
    'market.bearish': 'Bearish',
    'market.stable': 'Stable',
    'market.emptyTitle': 'No Matching Market Prices',
    'market.emptyMsg': 'Try searching for Paddy, Tomato, Onion, Cotton, Chilli...',

    // Image Gallery
    'gallery.title': 'Image Gallery',
    'gallery.subtitle': 'Browse beautiful crop photos and disease identification images',
    'gallery.cropsTab': 'Crops',
    'gallery.diseasesTab': 'Diseases',
    'gallery.searchPlaceholder': 'Search crops or diseases by name...',
    'gallery.itemsCount': 'items',
    'gallery.cereal': 'Cereal',
    'gallery.vegetable': 'Vegetable',
    'gallery.fruit': 'Fruit',
    'gallery.cashCrop': 'Cash Crop',
    'gallery.oilseed': 'Oilseed',
    'gallery.spice': 'Spice',
    'gallery.plantation': 'Plantation',
    'gallery.bestSeason': 'Best Season',
    'gallery.affects': 'Affects',
    'gallery.symptoms': 'Symptoms',

    // AI Assistant
    'ai.title': 'Smart AI Agriculture Assistant',
    'ai.subtitle': 'Ask anything about crops, soil, pest management, government schemes, and market prices',
    'ai.inputPlaceholder': 'Ask your farming question in any language...',
    'ai.send': 'Send',
    'ai.prompt1': 'Which crop is best for red soil in Tamil Nadu?',
    'ai.prompt2': 'How to control paddy stem borer naturally?',
    'ai.prompt3': 'What is the current market trend for tomato?',
    'ai.disclaimer': 'AI suggestions are generated based on agricultural datasets. Consult local experts for critical decisions.',
    'ai.listening': 'Listening now... Speak your farming question',
    'ai.voiceError': 'Voice input is not supported in this browser',
    'ai.analyzing': 'Analyzing farming data...',
    'ai.readAloud': 'Read Aloud',
    'ai.copyAnswer': 'Copy Answer',
    'ai.pillPaddy': '🌾 Paddy Guide',
    'ai.pillTomato': '🍅 Tomato Care',
    'ai.pillFertilizer': '🧪 NPK Fertilizer',
    'ai.pillPest': '🌿 Organic Pest',
    'ai.pillSchemes': '🏛️ Govt Schemes',
    'ai.pillMandi': '📈 Mandi Advice',

    // Reports
    'reports.title': 'Agricultural Advisory Reports',
    'reports.subtitle': 'Download and view seasonal farm advisory reports',
    'reports.downloadPdf': 'Download PDF Report',
    'reports.summary': 'Season Summary',
    'reports.soilHealth': 'Soil Health Index',
    'reports.farmOverview': 'Farm Overview',
    'reports.cropHistory': 'Crop Recommendation History',

    // Farm Details
    'farm.title': 'Farm & Soil Details',
    'farm.subtitle': 'Manage your farm parameters, soil nutrients, and irrigation setup',
    'farm.soilType': 'Soil Type',
    'farm.soilPh': 'Soil pH (1-14)',
    'farm.nitrogen': 'Available Nitrogen (N)',
    'farm.phosphorus': 'Available Phosphorus (P)',
    'farm.potassium': 'Available Potassium (K)',
    'farm.rainfall': 'Average Rainfall (mm)',
    'farm.temperature': 'Average Temperature (°C)',
    'farm.humidity': 'Average Humidity (%)',
    'farm.waterAvailability': 'Water Availability',
    'farm.irrigationMethod': 'Irrigation Method',
    'farm.season': 'Current Season',
    'farm.saveSuccess': 'Farm details saved successfully!',

    // Profile
    'profile.title': 'Farmer Profile',
    'profile.subtitle': 'Manage your personal details, location, and farm info',
    'profile.name': 'Full Name',
    'profile.phone': 'Phone Number',
    'profile.state': 'State',
    'profile.district': 'District',
    'profile.village': 'Village / Town',
    'profile.landSize': 'Total Land Size (Acres)',
    'profile.updateProfile': 'Update Profile',
    'profile.role': 'Account Role',
    'profile.memberSince': 'Member Since',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account, display preferences, and language',
    'settings.display': 'Display & Theme',
    'settings.mode': 'Light / Dark Mode',
    'settings.modeDesc': 'Switch between light and dark visual mode',
    'settings.language': 'Language (மொழி / भाषा / తెలుగు / Español)',
    'settings.selectLanguage': 'Select your preferred language for the whole app',
    'settings.notifications': 'Notifications & Alerts',
    'settings.pushNotif': 'Push Notifications',
    'settings.pushDesc': 'Receive instant alerts on weather changes & mandi rates',
    'settings.emailNotif': 'Email Advisory',
    'settings.emailDesc': 'Receive weekly crop advisory summaries via email',
    'settings.security': 'Account Security',
    'settings.changePassword': 'Change Password',

    // Landing Page
    'landing.heroTitle': 'Smart Agriculture & Crop Advisory for Farmers',
    'landing.heroSubtitle': 'Empowering Indian farmers with AI-driven crop suggestions, soil health analysis, pest detection, and live mandi market rates.',
    'landing.getStarted': 'Get Started Free',
    'landing.exploreFeatures': 'Explore Features',
    'landing.feature1Title': 'Smart Crop Suggestions',
    'landing.feature1Desc': 'Tailored crop suggestions matching your exact soil nutrients, pH, rainfall, and climate conditions.',
    'landing.feature2Title': 'Live Mandi Market Rates',
    'landing.feature2Desc': 'Track commodity prices across 100+ agricultural mandis to sell at maximum profit.',
    'landing.feature3Title': 'AI Disease Doctor & Vision',
    'landing.feature3Desc': 'Upload plant photos for instant pathogen identification with organic and chemical remedies.',
    'landing.feature4Title': 'Fertilizer & NPK Calculator',
    'landing.feature4Desc': 'Precise dosage calculation for Urea, DAP, Potash, and organic vermicompost per acre.',
    'landing.feature5Title': 'Hyper-local Weather Alerts',
    'landing.feature5Desc': '7-day rain, temperature, and wind forecasts tailored for farming and spraying schedules.',
    'landing.feature6Title': 'Multilingual AI Assistant',
    'landing.feature6Desc': 'Voice-enabled AI assistant available in English, தமிழ், हिंदी, తెలుగు, and Español.',
    'landing.statsFarmers': '10,000+ Farmers Assisted',
    'landing.statsAccuracy': '98% Recommendation Accuracy',
    'landing.statsMandis': '50+ Agricultural Mandis',

    // About Us & Contact
    'about.title': 'About CropAdvisory',
    'about.subtitle': 'Building digital agricultural intelligence to maximize farmer prosperity',
    'about.missionTitle': 'Our Mission',
    'about.missionDesc': 'To democratize advanced agricultural science, soil testing data, and market pricing intelligence for every farmer.',
    'contact.title': 'Contact Support',
    'contact.subtitle': 'Have a question or need technical help? We are here for you 24/7.',
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message / Inquiry',
    'contact.sendMsg': 'Send Message',
    'contact.sentSuccess': 'Your message has been sent. We will respond shortly!',

    // Footer
    'footer.tagline': 'Smart Agriculture & Crop Advisory System',
    'footer.rights': 'All rights reserved. Built for farmers with love.',
    'footer.quickLinks': 'Quick Links',
    'footer.tools': 'Advisory Tools',
    'footer.legal': 'Privacy & Terms',
  },

  ta: {
    // Navigation
    'nav.dashboard': 'முகப்பு பலகை',
    'nav.profile': 'சுயவிவரம்',
    'nav.farmDetails': 'பண்ணை விவரங்கள்',
    'nav.cropSuggestion': 'பயிர் பரிந்துரை',
    'nav.fertilizer': 'உர பரிந்துரை',
    'nav.weather': 'வானிலை',
    'nav.diseases': 'பயிர் நோய்கள்',
    'nav.gallery': 'படத் தொகுப்பு',
    'nav.marketPrices': 'சந்தை விலைகள்',
    'nav.aiAssistant': 'ஸ்மார்ட் உதவி',
    'nav.reports': 'அறிக்கைகள்',
    'nav.settings': 'அமைப்புகள்',
    'nav.adminTools': 'நிர்வாகக் கருவிகள்',
    'nav.contactUs': 'எங்களைத் தொடர்பு கொள்ள',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.needHelp': 'உதவி தேவையா?',
    'nav.helpSubtitle': 'உதவிக்கு எங்கள் ஆதரவு குழுவைத் தொடர்பு கொள்ளவும்',
    'nav.home': 'முகப்பு',
    'nav.login': 'உள்நுழைய',
    'nav.register': 'தொடங்கவும்',

    // Header & User Menu
    'header.notifications': 'அறிவிப்புகள்',
    'header.markRead': 'அனைத்தும் படித்ததாகக் குறிக்கவும்',
    'header.signOut': 'வெளியேறு',
    'header.myProfile': 'என் சுயவிவரம்',
    'header.settings': 'அமைப்புகள்',
    'header.new': 'புதியது',
    'header.noNotifications': 'புதிய அறிவிப்புகள் இல்லை',

    // Common Buttons & Labels
    'common.save': 'மாற்றங்களைச் சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.search': 'தேடு...',
    'common.select': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'common.loading': 'ஏற்றுகிறது...',
    'common.submit': 'சமர்ப்பி',
    'common.viewAll': 'அனைத்தையும் பார்',
    'common.details': 'விவரங்கள்',
    'common.status': 'நிலை',
    'common.date': 'தேதி',
    'common.action': 'செயல்',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.view': 'பார்',
    'common.viewDetails': 'விவரங்களைப் பார்க்க',
    'common.back': 'பின்செல்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.showing': 'காண்பிக்கப்படுகிறது',
    'common.to': 'முதல்',
    'common.of': 'மொத்தம்',
    'common.items': 'பதிவுகள்',
    'common.all': 'அனைத்தும்',
    'common.clear': 'அழி',
    'common.clearChat': 'அரட்டையை அழிக்கவும்',
    'common.copied': 'நகலெடுக்கப்பட்டது',
    'common.success': 'வெற்றி',
    'common.error': 'பிழை ஏற்பட்டது',
    'common.perQuintal': 'குவிண்டாலுக்கு',
    'common.acres': 'ஏக்கர்',

    // Dashboard
    'dash.welcome': 'வரவேற்கிறோம்',
    'dash.subtitle': 'இன்றைய உங்கள் பண்ணை விவரங்கள்',
    'dash.statCrops': 'மொத்த பயிர்கள்',
    'dash.statRecs': 'எனது பயிர் பரிந்துரைகள்',
    'dash.statMarket': 'சந்தை விலைகள்',
    'dash.statFarmers': 'பயன்படுத்தும் விவசாயிகள்',
    'dash.weatherTitle': 'வானிலை முன்னறிவிப்பு',
    'dash.humidity': 'ஈரப்பதம்',
    'dash.wind': 'காற்றின் வேகம்',
    'dash.chartWeather': 'அடுத்த 7 நாட்களின் வானிலை',
    'dash.chartSeasons': 'பருவகால பயிர்கள்',
    'dash.chartYield': 'எதிர்பார்க்கப்படும் மாத விளைச்சல்',
    'dash.recentRecs': 'சமீபத்திய பயிர் பரிந்துரைகள்',
    'dash.noRecs': 'இன்னும் பரிந்துரைகள் இல்லை. முதல் பரிந்துரையைப் பெறவும்!',
    'dash.getRecBtn': 'பயிர் பரிந்துரை பெறுக',
    'dash.match': 'பொருத்தம்',
    'dash.quickActions': 'விரைவுச் செயல்கள்',

    // Crop Recommendation
    'crop.title': 'பயிர் பரிந்துரை',
    'crop.subtitle': 'உங்கள் மண் மற்றும் தட்பவெப்ப நிலைக்கு ஏற்ற பயிர் பரிந்துரைகள்',
    'crop.nitrogen': 'நைட்ரஜன் (N)',
    'crop.phosphorus': 'பாஸ்பரஸ் (P)',
    'crop.potassium': 'பொட்டாசியம் (K)',
    'crop.ph': 'கார அமிலத்தன்மை (pH)',
    'crop.rainfall': 'மழைப்பொழிவு (மி.மீ)',
    'crop.temperature': 'வெப்பநிலை (°C)',
    'crop.humidity': 'ஈரப்பதம் (%)',
    'crop.soilType': 'மண் வகை',
    'crop.season': 'பருவம்',
    'crop.getRecommendation': 'பரிந்துரை பெறுக',
    'crop.results': 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    'crop.confidence': 'பொருத்தமான மதிப்பெண்',
    'crop.duration': 'வளர்ச்சி காலம்',
    'crop.waterReq': 'தேவையான நீர் அளவு',
    'crop.yield': 'எதிர்பார்க்கப்படும் மகசூல்',
    'crop.marketValue': 'சந்தை மதிப்பு',
    'crop.scientificName': 'அறிவியல் பெயர்',
    'crop.fertilizerPlan': 'உர திட்டம்',

    // Fertilizer
    'fertilizer.title': 'உரப் பரிந்துரை',
    'fertilizer.subtitle': 'அதிக மகசூலுக்குத் தேவையான உர அளவைக் கணக்கிடுங்கள்',
    'fertilizer.crop': 'பயிரைத் தேர்ந்தெடுக்கவும்',
    'fertilizer.area': 'நில பரப்பளவு (ஏக்கர்)',
    'fertilizer.currentN': 'தற்போதைய நைட்ரஜன் (கிலோ/ஏக்கர்)',
    'fertilizer.currentP': 'தற்போதைய பாஸ்பரஸ் (கிலோ/ஏக்கர்)',
    'fertilizer.currentK': 'தற்போதைய பொட்டாசியம் (கிலோ/ஏக்கர்)',
    'fertilizer.calculate': 'உர அளவைக் கணக்கிடு',
    'fertilizer.result': 'பரிந்துரைக்கப்படும் உரங்கள்',
    'fertilizer.urea': 'யுரியா (Urea 46% N)',
    'fertilizer.dap': 'டிஏபி (DAP 18:46:0)',
    'fertilizer.mop': 'பொட்டாஷ் (MOP 60% K)',
    'fertilizer.organic': 'இயற்கை உர மாற்றுக்கள்',
    'fertilizer.schedule': 'உரமிடும் கால அட்டவணை',
    'fertilizer.precautions': 'முன்னெச்சரிக்கைகள் மற்றும் பாதுகாப்பு',

    // Weather
    'weather.title': 'வானிலை ஆலோசனை',
    'weather.subtitle': 'உள்ளூர் வானிலை முன்னறிவிப்பு மற்றும் விவசாய விழிப்பூட்டல்கள்',
    'weather.searchLoc': 'இடத்தைத் தேடுக...',
    'weather.useMyLocation': 'தற்போதைய இடத்தைப் பயன்படுத்து',
    'weather.tempMax': 'அதிகபட்ச வெப்பநிலை',
    'weather.tempMin': 'குறைந்தபட்ச வெப்பநிலை',
    'weather.rainProb': 'மழைப்பொழிவு வாய்ப்பு',
    'weather.farmingTip': 'விவசாய ஆலோசனை',
    'weather.rainAlert': 'மழை வாய்ப்பு உள்ளது! பூச்சிக்கொல்லி தெளிப்பதை ஒத்திவைக்கவும்.',
    'weather.uvIndex': 'புற ஊதா குறியீடு (UV)',
    'weather.pressure': 'வளிமண்டல அழுத்தம்',
    'weather.visibility': 'தெரிவுதிறன்',
    'weather.sunrise': 'சூரிய உதயம்',
    'weather.sunset': 'சூரிய அஸ்தமனம்',
    'weather.hourlyForecast': 'மணிநேர முன்னறிவிப்பு',
    'weather.weeklyForecast': '7-நாள் முன்னறிவிப்பு',

    // Diseases
    'diseases.title': 'பயிர் நோய் மற்றும் பூச்சி கண்டறிதல்',
    'diseases.subtitle': 'பயிர் நோய்களைக் கண்டறிந்து இயற்கை மற்றும் ரசாயன தீர்வுகளைப் பெறுங்கள்',
    'diseases.inspectBtn': 'பயிர் படத்தை ஆய்வு செய்க',
    'diseases.uploadImg': 'பயிர் படத்தைப் பதிவேற்றவும்',
    'diseases.analyzing': 'பயிர் ஆரோக்கியம் ஆய்வு செய்யப்படுகிறது...',
    'diseases.examiningLeaves': 'AI இலைகளில் உள்ள நோய்களைக் கண்டறிகிறது...',
    'diseases.diagnosisTitle': 'AI நோயறிதல் அறிக்கை',
    'diseases.symptoms': 'அறிகுறிகள்',
    'diseases.causes': 'முதன்மை காரணங்கள்',
    'diseases.prevention': 'தடுப்பு முறைகள்',
    'diseases.treatment': 'சிகிச்சை மற்றும் கட்டுப்பாடு',
    'diseases.chemical': 'ரசாயன முறை தீர்வு',
    'diseases.organic': 'இயற்கை முறை தீர்வு',
    'diseases.viewGuide': 'சிகிச்சை வழிகாட்டியைப் பார்க்க',
    'diseases.emptyTitle': 'பொருத்தமான நோய்கள் எதுவும் கிடைக்கவில்லை',
    'diseases.emptyMsg': 'நெல், தக்காளி, கோதுமை, வாழை, பருத்தி போன்ற பயிர்களைத் தேடுங்கள்...',

    // Market Prices
    'market.title': 'சந்தை விலைகள் & போக்குகள்',
    'market.subtitle': 'நேரலை மண்டிகளின் விவசாய விலை விவரங்கள்',
    'market.topGainer': 'இன்றைய அதிக விலை ஏற்றம்',
    'market.avgRate': 'சராசரி மண்டி விலை',
    'market.activeMandis': 'செயலில் உள்ள மண்டிகள்',
    'market.sentiment': 'சந்தை போக்கு',
    'market.commodity': 'விளைபொருள்',
    'market.marketName': 'சந்தை / மண்டி',
    'market.minPrice': 'குறைந்தபட்ச விலை',
    'market.maxPrice': 'அதிகபட்ச விலை',
    'market.modalPrice': 'சராசரி விலை',
    'market.prevPrice': 'முந்தைய விலை',
    'market.trend24h': '24 மணிநேர போக்கு',
    'market.district': 'மாவட்டம்',
    'market.filterCrop': 'பயிரின்படி வடிகட்டவும்',
    'market.allMandis': 'அனைத்து மண்டிகள் / சந்தைகள்',
    'market.bullish': 'விலை ஏற்றம்',
    'market.bearish': 'விலை சரிவு',
    'market.stable': 'நிலையானது',
    'market.emptyTitle': 'சந்தை விலைகள் கிடைக்கவில்லை',
    'market.emptyMsg': 'நெல், தக்காளி, வெங்காயம், பருத்தி, மிளகாய் போன்றவற்றைத் தேடவும்...',

    // Image Gallery
    'gallery.title': 'படத் தொகுப்பு',
    'gallery.subtitle': 'அழகான பயிர் புகைப்படங்கள் மற்றும் நோய் அடையாள படங்கள்',
    'gallery.cropsTab': 'பயிர்கள்',
    'gallery.diseasesTab': 'நோய்கள்',
    'gallery.searchPlaceholder': 'பயிர் அல்லது நோயின் பெயரைத் தேடுக...',
    'gallery.itemsCount': 'படங்கள்',
    'gallery.cereal': 'தானியங்கள்',
    'gallery.vegetable': 'காய்கறிகள்',
    'gallery.fruit': 'பழங்கள்',
    'gallery.cashCrop': 'பணப்பயிர்கள்',
    'gallery.oilseed': 'எண்ணெய் வித்துக்கள்',
    'gallery.spice': 'நறுமணப் பயிர்கள்',
    'gallery.plantation': 'தோட்டப் பயிர்கள்',
    'gallery.bestSeason': 'ஏற்ற பருவம்',
    'gallery.affects': 'பாதிக்கும் பயிர்',
    'gallery.symptoms': 'அறிகுறிகள்',

    // AI Assistant
    'ai.title': 'ஸ்மார்ட் AI விவசாய உதவி',
    'ai.subtitle': 'பயிர்கள், மண், பூச்சி மேலாண்மை, அரசு திட்டங்கள் மற்றும் சந்தை விலைகள் பற்றி கேளுங்கள்',
    'ai.inputPlaceholder': 'எந்த மொழியிலும் உங்கள் விவசாயக் கேள்வியைக் கேளுங்கள்...',
    'ai.send': 'அனுப்பு',
    'ai.prompt1': 'தமிழ்நாட்டில் செம்மண்ணிற்கு ஏற்ற பயிர் எது?',
    'ai.prompt2': 'நெல் குருத்துப்பூச்சியை இயற்கை முறையில் கட்டுப்படுத்துவது எப்படி?',
    'ai.prompt3': 'தக்காளிக்கான தற்போதைய சந்தை விலை நிலவரம் என்ன?',
    'ai.disclaimer': 'AI பரிந்துரைகள் விவசாயத் தரவுகளின் அடிப்படையில் வழங்கப்படுகின்றன. முக்கியமான முடிவுகளுக்கு உள்ளூர் நிபுணர்களைக் கலந்தாலோசிக்கவும்.',
    'ai.listening': 'கேட்கிறது... உங்கள் விவசாயக் கேள்வியைப் பேசுங்கள்',
    'ai.voiceError': 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை',
    'ai.analyzing': 'விவசாயத் தரவுகள் ஆய்வு செய்யப்படுகின்றன...',
    'ai.readAloud': 'சத்தமாக வாசிக்கவும்',
    'ai.copyAnswer': 'பதிலை நகலெடு',
    'ai.pillPaddy': '🌾 நெல் சாகுபடி',
    'ai.pillTomato': '🍅 தக்காளி நோய்',
    'ai.pillFertilizer': '🧪 உர அளவு (NPK)',
    'ai.pillPest': '🌿 இயற்கை பூச்சி மருந்து',
    'ai.pillSchemes': '🏛️ அரசு மானியங்கள்',
    'ai.pillMandi': '📈 சந்தை விலை உத்திகள்',

    // Reports
    'reports.title': 'விவசாய ஆலோசனை அறிக்கைகள்',
    'reports.subtitle': 'பருவகால விவசாய அறிக்கைகளைப் பதிவிறக்கம் செய்து பார்க்கவும்',
    'reports.downloadPdf': 'PDF அறிக்கையைப் பதிவிறக்கு',
    'reports.summary': 'பருவகால சுருக்கம்',
    'reports.soilHealth': 'மண் வள குறியீடு',
    'reports.farmOverview': 'பண்ணை கண்ணோட்டம்',
    'reports.cropHistory': 'பயிர் பரிந்துரை வரலாறு',

    // Farm Details
    'farm.title': 'பண்ணை மற்றும் மண் விவரங்கள்',
    'farm.subtitle': 'மண் ஊட்டச்சத்துக்கள் மற்றும் பாசன முறைகளை நிர்வகிக்கவும்',
    'farm.soilType': 'மண் வகை',
    'farm.soilPh': 'கார அமிலத்தன்மை (pH 1-14)',
    'farm.nitrogen': 'கிடைக்கக்கூடிய நைட்ரஜன் (N)',
    'farm.phosphorus': 'கிடைக்கக்கூடிய பாஸ்பரஸ் (P)',
    'farm.potassium': 'கிடைக்கக்கூடிய பொட்டாசியம் (K)',
    'farm.rainfall': 'சராசரி மழைப்பொழிவு (மி.மீ)',
    'farm.temperature': 'சராசரி வெப்பநிலை (°C)',
    'farm.humidity': 'சராசரி ஈரப்பதம் (%)',
    'farm.waterAvailability': 'நீர் இருப்பு நிலை',
    'farm.irrigationMethod': 'பாசன முறை',
    'farm.season': 'தற்போதைய பருவம்',
    'farm.saveSuccess': 'பண்ணை விவரங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!',

    // Profile
    'profile.title': 'விவசாயி சுயவிவரம்',
    'profile.subtitle': 'உங்கள் விவரங்கள் மற்றும் நில தகவல்களை நிர்வகிக்கவும்',
    'profile.name': 'முழு பெயர்',
    'profile.phone': 'தொலைபேசி எண்',
    'profile.state': 'மாநிலம்',
    'profile.district': 'மாவட்டம்',
    'profile.village': 'கிராமம் / ஊர்',
    'profile.landSize': 'மொத்த நில பரப்பளவு (ஏக்கர்)',
    'profile.updateProfile': 'சுயவிவரத்தைப் புதுப்பி',
    'profile.role': 'கணக்கு வகை',
    'profile.memberSince': 'உறுப்பினர் காலம்',

    // Settings
    'settings.title': 'அமைப்புகள்',
    'settings.subtitle': 'உங்கள் கணக்கு, திரை தோற்றம் மற்றும் மொழியை நிர்வகிக்கவும்',
    'settings.display': 'திரை தோற்றம் மற்றும் தீம்',
    'settings.mode': 'வெளிச்சம் / இருள் பயன்முறை',
    'settings.modeDesc': 'வெளிச்சம் மற்றும் இருள் பயன்முறைக்கு மாறவும்',
    'settings.language': 'மொழி (Language)',
    'settings.selectLanguage': 'முழு பயன்பாட்டிற்கும் உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
    'settings.notifications': 'அறிவிப்புகள் மற்றும் விழிப்பூட்டல்கள்',
    'settings.pushNotif': 'புஷ் அறிவிப்புகள்',
    'settings.pushDesc': 'வானிலை & சந்தை விலை விழிப்பூட்டல்களை உடனடியாகப் பெறவும்',
    'settings.emailNotif': 'மின்னஞ்சல் ஆலோசனை',
    'settings.emailDesc': 'வாராந்திர ஆலோசனை அறிக்கைகளை மின்னஞ்சலில் பெறவும்',
    'settings.security': 'பாதுகாப்பு',
    'settings.changePassword': 'கடவுச்சொல்லை மாற்றவும்',

    // Landing Page
    'landing.heroTitle': 'விவசாயிகளுக்கான ஸ்மார்ட் விவசாய மற்றும் பயிர் ஆலோசனை',
    'landing.heroSubtitle': 'AI வழிகாட்டுதல், மண் பகுப்பாய்வு, நோய் கண்டறிதல் மற்றும் நேரலை மண்டி விலைகள் மூலம் விவசாயிகளுக்கு அதிக மகசூல் மற்றும் லாபம்.',
    'landing.getStarted': 'இலவசமாகத் தொடங்குங்கள்',
    'landing.exploreFeatures': 'அம்சங்களை ஆராயுங்கள்',
    'landing.feature1Title': 'ஸ்மார்ட் பயிர் பரிந்துரை',
    'landing.feature1Desc': 'மண் சத்துக்கள், pH, மழை மற்றும் தட்பவெப்ப நிலைக்கு ஏற்ற பயிர் தேர்வுகள்.',
    'landing.feature2Title': 'நேரலை சந்தை விலைகள்',
    'landing.feature2Desc': '100+ விவசாய மண்டிகளின் விலைகளை அறிந்து அதிக லாபத்திற்கு விற்கவும்.',
    'landing.feature3Title': 'AI நோய் மருத்துவர்',
    'landing.feature3Desc': 'பயிர் படங்களை பதிவேற்றி உடனடியாக நோய் மற்றும் இயற்கை தீர்வுகளைப் பெறுங்கள்.',
    'landing.feature4Title': 'உரக் கணக்கீடு (NPK)',
    'landing.feature4Desc': 'யுரியா, டிஏபி, பொட்டாஷ் மற்றும் மண்புழு உரத்தின் சரியான அளவு.',
    'landing.feature5Title': 'துல்லியமான வானிலை',
    'landing.feature5Desc': '7-நாள் மழை மற்றும் வெப்பநிலை முன்னறிவிப்புகள்.',
    'landing.feature6Title': 'பன்மொழி AI உதவியாளர்',
    'landing.feature6Desc': 'தமிழ், ஆங்கிலம், இந்தி, தெலுங்கு மற்றும் ஸ்பானிஷ் மொழிகளில் குரல் வழி உதவி.',
    'landing.statsFarmers': '10,000+ விவசாயிகள் பயன் பெற்றுள்ளனர்',
    'landing.statsAccuracy': '98% துல்லியமான பரிந்துரை',
    'landing.statsMandis': '50+ நேரலை மண்டிகள்',

    // About & Contact
    'about.title': 'CropAdvisory பற்றி',
    'about.subtitle': 'விவசாயிகளின் வாழ்வாதாரத்தை உயர்த்த நவீன தொழில்நுட்பம்',
    'about.missionTitle': 'எங்கள் நோக்கம்',
    'about.missionDesc': 'ஒவ்வொரு விவசாயிக்கும் அதிநவீன விவசாய அறிவியல் மற்றும் சந்தை தகவல்களை எளிதாகக் கிடைக்கச் செய்தல்.',
    'contact.title': 'ஆதரவு தொடர்பு',
    'contact.subtitle': 'கேள்விகள் அல்லது உதவி தேவையா? நாங்கள் 24/7 உங்களுக்கு உதவ தயாராக உள்ளோம்.',
    'contact.name': 'உங்கள் பெயர்',
    'contact.email': 'உங்கள் மின்னஞ்சல்',
    'contact.message': 'உங்கள் செய்தி / கேள்வி',
    'contact.sendMsg': 'செய்தியை அனுப்பவும்',
    'contact.sentSuccess': 'உங்கள் செய்தி அனுப்பப்பட்டது. விரைவில் பதிலளிப்போம்!',

    // Footer
    'footer.tagline': 'ஸ்மார்ட் விவசாயம் மற்றும் பயிர் ஆலோசனை தளம்',
    'footer.rights': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. விவசாயிகளுக்காக உருவாக்கப்பட்டது.',
    'footer.quickLinks': 'விரைவு இணைப்புகள்',
    'footer.tools': 'ஆலோசனை கருவிகள்',
    'footer.legal': 'தனியுரிமை & விதிமுறைகள்',
  },

  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.farmDetails': 'खेत का विवरण',
    'nav.cropSuggestion': 'फसल सुझाव',
    'nav.fertilizer': 'उर्वरक सलाह',
    'nav.weather': 'मौसम',
    'nav.diseases': 'फसल बीमारियां',
    'nav.gallery': 'इमेज गैलरी',
    'nav.marketPrices': 'बाजार मूल्य',
    'nav.aiAssistant': 'स्मार्ट सहायक',
    'nav.reports': 'रिपोर्ट',
    'nav.settings': 'सेटिंग्स',
    'nav.adminTools': 'एडमिन टूल्स',
    'nav.contactUs': 'संपर्क करें',
    'nav.about': 'हमारे बारे में',
    'nav.needHelp': 'क्या सहायता चाहिए?',
    'nav.helpSubtitle': 'सहायता के लिए हमारी टीम से संपर्क करें',
    'nav.home': 'होम',
    'nav.login': 'साइन इन',
    'nav.register': 'शुरू करें',

    // Header & User Menu
    'header.notifications': 'सूचनाएं',
    'header.markRead': 'सभी को पढ़ा हुआ चिन्हित करें',
    'header.signOut': 'साइन आउट',
    'header.myProfile': 'मेरी प्रोफ़ाइल',
    'header.settings': 'सेटिंग्स',
    'header.new': 'नया',
    'header.noNotifications': 'कोई नई सूचना नहीं है',

    // Common Buttons & Labels
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.search': 'खोजें...',
    'common.select': 'भाषा चुनें',
    'common.loading': 'लोड हो रहा है...',
    'common.submit': 'सबमिट करें',
    'common.viewAll': 'सभी देखें',
    'common.details': 'विवरण',
    'common.status': 'स्थिति',
    'common.date': 'तारीख',
    'common.action': 'कार्रवाई',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.view': 'देखें',
    'common.viewDetails': 'विवरण देखें',
    'common.back': 'पीछे जाएं',
    'common.next': 'आगे',
    'common.previous': 'पिछला',
    'common.showing': 'दिखाया जा रहा है',
    'common.to': 'से',
    'common.of': 'का कुल',
    'common.items': 'रिकॉर्ड',
    'common.all': 'सभी',
    'common.clear': 'साफ़ करें',
    'common.clearChat': 'चैट साफ़ करें',
    'common.copied': 'कॉपी किया गया',
    'common.success': 'सफल',
    'common.error': 'त्रुटि हुई',
    'common.perQuintal': 'प्रति क्विंटल',
    'common.acres': 'एकड़',

    // Dashboard
    'dash.welcome': 'स्वागत है',
    'dash.subtitle': 'आज आपके खेत की जानकारी',
    'dash.statCrops': 'कुल फसलें',
    'dash.statRecs': 'मेरी फसल सलाह',
    'dash.statMarket': 'बाजार मूल्य',
    'dash.statFarmers': 'उपयोगकर्ता किसान',
    'dash.weatherTitle': 'मौसम का पूर्वानुमान',
    'dash.humidity': 'नमी (आर्द्रता)',
    'dash.wind': 'हवा की गति',
    'dash.chartWeather': 'अगले 7 दिनों का मौसम',
    'dash.chartSeasons': 'सीजन के अनुसार फसलें',
    'dash.chartYield': 'अनुमानित मासिक उपज',
    'dash.recentRecs': 'हाल की फसल सलाह',
    'dash.noRecs': 'अभी तक कोई फसल सलाह नहीं है। पहली सलाह प्राप्त करें!',
    'dash.getRecBtn': 'फसल सुझाव प्राप्त करें',
    'dash.match': 'मैच',
    'dash.quickActions': 'त्वरित कार्रवाई',

    // Crop Recommendation
    'crop.title': 'फसल सुझाव',
    'crop.subtitle': 'अपनी मिट्टी और जलवायु के अनुसार स्मार्ट फसल सलाह प्राप्त करें',
    'crop.nitrogen': 'नाइट्रोजन (N)',
    'crop.phosphorus': 'फास्फोरस (P)',
    'crop.potassium': 'पोटेशियम (K)',
    'crop.ph': 'pH स्तर',
    'crop.rainfall': 'वर्षा (मिमी)',
    'crop.temperature': 'तापमान (°C)',
    'crop.humidity': 'नमी (%)',
    'crop.soilType': 'मिट्टी का प्रकार',
    'crop.season': 'मौसम / सीजन',
    'crop.getRecommendation': 'सलाह प्राप्त करें',
    'crop.results': 'अनुशंसित फसलें',
    'crop.confidence': 'उपयुक्तता स्कोर',
    'crop.duration': 'फसल की अवधि',
    'crop.waterReq': 'जल की आवश्यकता',
    'crop.yield': 'अनुमानित उपज',
    'crop.marketValue': 'बाजार मूल्य',
    'crop.scientificName': 'वैज्ञानिक नाम',
    'crop.fertilizerPlan': 'उर्वरक योजना',

    // Fertilizer
    'fertilizer.title': 'उर्वरक सलाह',
    'fertilizer.subtitle': 'इष्टतम उपज के लिए सटीक उर्वरक खुराक की गणना करें',
    'fertilizer.crop': 'फसल चुनें',
    'fertilizer.area': 'भूमि का क्षेत्रफल (एकड़)',
    'fertilizer.currentN': 'वर्तमान नाइट्रोजन (किग्रा/एकड़)',
    'fertilizer.currentP': 'वर्तमान फास्फोरस (किग्रा/एकड़)',
    'fertilizer.currentK': 'वर्तमान पोटेशियम (किग्रा/एकड़)',
    'fertilizer.calculate': 'खुराक की गणना करें',
    'fertilizer.result': 'अनुशंसित उर्वरक',
    'fertilizer.urea': 'यूरिया (Urea 46% N)',
    'fertilizer.dap': 'डीएपी (DAP 18:46:0)',
    'fertilizer.mop': 'एमओपी (MOP / पोटैश)',
    'fertilizer.organic': 'जैविक विकल्प',
    'fertilizer.schedule': 'खाद देने की समय सारणी',
    'fertilizer.precautions': 'सावधानियां एवं सुरक्षा',

    // Weather
    'weather.title': 'मौसम सलाह',
    'weather.subtitle': 'स्थानीय मौसम पूर्वानुमान और कृषि चेतावनियां',
    'weather.searchLoc': 'स्थान या जिला खोजें...',
    'weather.useMyLocation': 'वर्तमान स्थान का उपयोग करें',
    'weather.tempMax': 'अधिकतम तापमान',
    'weather.tempMin': 'न्यूनतम तापमान',
    'weather.rainProb': 'बारिश की संभावना',
    'weather.farmingTip': 'कृषि सलाह',
    'weather.rainAlert': 'बारिश की संभावना है! कीटनाशक छिड़काव स्थगित करें।',
    'weather.uvIndex': 'यूवी सूचकांक (UV)',
    'weather.pressure': 'वायुमंडलीय दबाव',
    'weather.visibility': 'दृश्यता',
    'weather.sunrise': 'सूर्योदय',
    'weather.sunset': 'सूर्यास्त',
    'weather.hourlyForecast': 'प्रति घंटा पूर्वानुमान',
    'weather.weeklyForecast': '7-दिवसीय पूर्वानुमान',

    // Diseases
    'diseases.title': 'फसल रोग एवं कीट पहचान',
    'diseases.subtitle': 'फसल रोगों की पहचान करें और जैविक व रासायनिक समाधान पाएं',
    'diseases.inspectBtn': 'फसल फोटो की जांच करें',
    'diseases.uploadImg': 'फसल की फोटो अपलोड करें',
    'diseases.analyzing': 'फसल स्वास्थ्य की जांच हो रही है...',
    'diseases.examiningLeaves': 'हमारा AI पत्तियों के रोगों का विश्लेषण कर रहा है...',
    'diseases.diagnosisTitle': 'AI रोग निदान रिपोर्ट',
    'diseases.symptoms': 'लक्षण',
    'diseases.causes': 'मुख्य कारण',
    'diseases.prevention': 'बचाव के तरीके',
    'diseases.treatment': 'उपचार और नियंत्रण',
    'diseases.chemical': 'रासायनिक उपाय',
    'diseases.organic': 'जैविक उपाय',
    'diseases.viewGuide': 'उपचार गाइड देखें',
    'diseases.emptyTitle': 'कोई रोग नहीं मिला',
    'diseases.emptyMsg': 'धान, टमाटर, गेहूं, केला, कपास जैसी फसलों को खोजें...',

    // Market Prices
    'market.title': 'बाजार मूल्य और रुझान',
    'market.subtitle': 'लाइव मंडी भाव और बाजार दर विश्लेषण',
    'market.topGainer': 'आज का शीर्ष तेजी वाला भाव',
    'market.avgRate': 'औसत मंडी दर',
    'market.activeMandis': 'सक्रिय मंडियां',
    'market.sentiment': 'बाजार का रुझान',
    'market.commodity': 'फसल / जिंस',
    'market.marketName': 'बाजार / मंडी',
    'market.minPrice': 'न्यूनतम मूल्य',
    'market.maxPrice': 'अधिकतम मूल्य',
    'market.modalPrice': 'मॉडल मूल्य',
    'market.prevPrice': 'पिछला मूल्य',
    'market.trend24h': '24 घंटे का रुझान',
    'market.district': 'जिला',
    'market.filterCrop': 'फसल के अनुसार फ़िल्टर करें',
    'market.allMandis': 'सभी मंडियां / बाजार',
    'market.bullish': 'तेजी',
    'market.bearish': 'मंदी',
    'market.stable': 'स्थिर',
    'market.emptyTitle': 'बाजार मूल्य नहीं मिले',
    'market.emptyMsg': 'धान, टमाटर, प्याज, कपास, मिर्च आदि खोजें...',

    // Image Gallery
    'gallery.title': 'इमेज गैलरी',
    'gallery.subtitle': 'सुंदर फसल तस्वीरें और रोग पहचान छवियां देखें',
    'gallery.cropsTab': 'फसलें',
    'gallery.diseasesTab': 'रोग एवं कीट',
    'gallery.searchPlaceholder': 'फसल या रोग का नाम खोजें...',
    'gallery.itemsCount': 'आइटम',
    'gallery.cereal': 'अनाज',
    'gallery.vegetable': 'सब्जियां',
    'gallery.fruit': 'फल',
    'gallery.cashCrop': 'नकदी फसलें',
    'gallery.oilseed': 'तिलहन',
    'gallery.spice': 'मसाले',
    'gallery.plantation': 'बागवानी',
    'gallery.bestSeason': 'सर्वोत्तम सीजन',
    'gallery.affects': 'प्रभावित फसल',
    'gallery.symptoms': 'लक्षण',

    // AI Assistant
    'ai.title': 'स्मार्ट AI कृषि सहायक',
    'ai.subtitle': 'फसलों, मिट्टी, कीट प्रबंधन, सरकारी योजनाओं और मंडी भाव के बारे में कुछ भी पूछें',
    'ai.inputPlaceholder': 'किसी भी भाषा में अपना कृषि संबंधी प्रश्न पूछें...',
    'ai.send': 'भेजें',
    'ai.prompt1': 'लाल मिट्टी के लिए सबसे अच्छी फसल कौन सी है?',
    'ai.prompt2': 'धान के तना छेदक कीट को प्राकृतिक रूप से कैसे नियंत्रित करें?',
    'ai.prompt3': 'टमाटर के लिए वर्तमान बाजार मूल्य का रुझान क्या है?',
    'ai.disclaimer': 'AI सुझाव कृषि डेटा के आधार पर तैयार किए जाते हैं। महत्वपूर्ण निर्णयों के लिए स्थानीय विशेषज्ञों से सलाह लें।',
    'ai.listening': 'सुन रहा हूँ... अपना सवाल बोलें',
    'ai.voiceError': 'इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है',
    'ai.analyzing': 'कृषि डेटा का विश्लेषण किया जा रहा है...',
    'ai.readAloud': 'बोलकर सुनाएं',
    'ai.copyAnswer': 'उत्तर कॉपी करें',
    'ai.pillPaddy': '🌾 धान की खेती',
    'ai.pillTomato': '🍅 टमाटर रोग',
    'ai.pillFertilizer': '🧪 उर्वरक (NPK)',
    'ai.pillPest': '🌿 जैविक कीटनाशक',
    'ai.pillSchemes': '🏛️ सरकारी योजनाएं',
    'ai.pillMandi': '📈 मंडी भाव रणनीति',

    // Reports
    'reports.title': 'कृषि सलाहकार रिपोर्ट',
    'reports.subtitle': 'मौसमी कृषि रिपोर्ट डाउनलोड करें और देखें',
    'reports.downloadPdf': 'PDF रिपोर्ट डाउनलोड करें',
    'reports.summary': 'सीजन का सारांश',
    'reports.soilHealth': 'मिट्टी स्वास्थ्य सूचकांक',
    'reports.farmOverview': 'खेत का अवलोकन',
    'reports.cropHistory': 'फसल सलाह इतिहास',

    // Farm Details
    'farm.title': 'खेत एवं मिट्टी का विवरण',
    'farm.subtitle': 'मिट्टी के पोषक तत्वों और सिंचाई प्रणाली का प्रबंधन करें',
    'farm.soilType': 'मिट्टी का प्रकार',
    'farm.soilPh': 'मिट्टी का pH (1-14)',
    'farm.nitrogen': 'उपलब्ध नाइट्रोजन (N)',
    'farm.phosphorus': 'उपलब्ध फास्फोरस (P)',
    'farm.potassium': 'उपलब्ध पोटेशियम (K)',
    'farm.rainfall': 'औसत वर्षा (मिमी)',
    'farm.temperature': 'औसत तापमान (°C)',
    'farm.humidity': 'औसत नमी (%)',
    'farm.waterAvailability': 'पानी की उपलब्धता',
    'farm.irrigationMethod': 'सिंचाई की विधि',
    'farm.season': 'वर्तमान सीजन',
    'farm.saveSuccess': 'खेत का विवरण सफलतापूर्वक सहेजा गया!',

    // Profile
    'profile.title': 'किसान प्रोफ़ाइल',
    'profile.subtitle': 'अपनी व्यक्तिगत जानकारी और खेत का विवरण प्रबंधित करें',
    'profile.name': 'पूरा नाम',
    'profile.phone': 'फ़ोन नंबर',
    'profile.state': 'राज्य',
    'profile.district': 'जिला',
    'profile.village': 'गांव / कस्बा',
    'profile.landSize': 'कुल भूमि (एकड़)',
    'profile.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'profile.role': 'खाता भूमिका',
    'profile.memberSince': 'सदस्य बने',

    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपने खाते, डिस्पले और भाषा का प्रबंधन करें',
    'settings.display': 'डिस्पले और थीम',
    'settings.mode': 'लाइट / डार्क मोड',
    'settings.modeDesc': 'लाइट और डार्क मोड के बीच स्विच करें',
    'settings.language': 'भाषा (Language)',
    'settings.selectLanguage': 'पूरी ऐप के लिए अपनी पसंदीदा भाषा चुनें',
    'settings.notifications': 'सूचनाएं और अलर्ट',
    'settings.pushNotif': 'पुश सूचनाएं',
    'settings.pushDesc': 'मौसम और मंडी भाव में बदलाव के तुरंत अलर्ट पाएं',
    'settings.emailNotif': 'ईमेल सलाह',
    'settings.emailDesc': 'ईमेल के माध्यम से साप्ताहिक रिपोर्ट प्राप्त करें',
    'settings.security': 'सुरक्षा',
    'settings.changePassword': 'पासवर्ड बदलें',

    // Landing Page
    'landing.heroTitle': 'किसानों के लिए स्मार्ट कृषि एवं फसल सलाह',
    'landing.heroSubtitle': 'AI आधारित फसल सुझाव, मिट्टी विश्लेषण, कीट पहचान और लाइव मंडी भावों के साथ किसानों की उपज और लाभ बढ़ाएं।',
    'landing.getStarted': 'निःशुल्क शुरू करें',
    'landing.exploreFeatures': 'सुविधाएं देखें',
    'landing.feature1Title': 'स्मार्ट फसल चयन',
    'landing.feature1Desc': 'आपकी मिट्टी, पोषक तत्व, वर्षा और मौसम के अनुकूल सबसे उपयुक्त फसलें।',
    'landing.feature2Title': 'लाइव मंडी भाव',
    'landing.feature2Desc': '100+ कृषि मंडियों के लाइव भाव ट्रैक करें और सही समय पर बेचें।',
    'landing.feature3Title': 'AI कीट एवं रोग डॉक्टर',
    'landing.feature3Desc': 'फोटो अपलोड कर तुरंत रोग की पहचान और जैविक उपाय पाएं।',
    'landing.feature4Title': 'उर्वरक (NPK) कैलकुलेटर',
    'landing.feature4Desc': 'यूरिया, डीएपी और पोटाश की प्रति एकड़ सटीक मात्रा की गणना।',
    'landing.feature5Title': 'मौसम अलर्ट',
    'landing.feature5Desc': '7-दिवसीय सटीक मौसम, बारिश और छिड़काव की सलाह।',
    'landing.feature6Title': 'बहुभाषी AI सहायक',
    'landing.feature6Desc': 'हिंदी, तमिल, तेलुगु, अंग्रेजी और स्पैनिश में वॉयस चैट की सुविधा।',
    'landing.statsFarmers': '10,000+ संतुष्ट किसान',
    'landing.statsAccuracy': '98% सटीक अनुशंसाएं',
    'landing.statsMandis': '50+ सक्रिय मंडियां',

    // About & Contact
    'about.title': 'CropAdvisory के बारे में',
    'about.subtitle': 'किसानों की समृद्धि के लिए डिजिटल कृषि विज्ञान',
    'about.missionTitle': 'हमारा उद्देश्य',
    'about.missionDesc': 'हर किसान तक आधुनिक कृषि विज्ञान और बाजार की सही जानकारी आसानी से पहुंचाना।',
    'contact.title': 'सहायता संपर्क',
    'contact.subtitle': 'कोई प्रश्न है? हमारी टीम आपकी सहायता के लिए 24/7 उपलब्ध है।',
    'contact.name': 'आपका नाम',
    'contact.email': 'आपका ईमेल',
    'contact.message': 'आपका संदेश',
    'contact.sendMsg': 'संदेश भेजें',
    'contact.sentSuccess': 'संदेश भेजा गया। हम जल्द ही संपर्क करेंगे!',

    // Footer
    'footer.tagline': 'स्मार्ट कृषि एवं फसल सलाहकार प्रणाली',
    'footer.rights': 'सर्वाधिकार सुरक्षित। किसानों की सेवा में समर्पित।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.tools': 'सलाहकार उपकरण',
    'footer.legal': 'गोपनीयता एवं शर्तें',
  },

  te: {
    // Navigation
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.profile': 'రైతు ప్రొఫైల్',
    'nav.farmDetails': 'పొలం వివరాలు',
    'nav.cropSuggestion': 'పంట సూచనలు',
    'nav.fertilizer': 'ఎరువుల వివరాలు',
    'nav.weather': 'వాతావరణం',
    'nav.diseases': 'పంట తెగుళ్లు',
    'nav.gallery': 'చిత్ర గ్యాలరీ',
    'nav.marketPrices': 'మార్కెట్ ధరలు',
    'nav.aiAssistant': 'స్మార్ట్ AI సహాయకుడు',
    'nav.reports': 'నివేదికలు',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.adminTools': 'అడ్మిన్ టూల్స్',
    'nav.contactUs': 'మమ్మల్ని సంప్రదించండి',
    'nav.about': 'మా గురించి',
    'nav.needHelp': 'సహాయం కావాలా?',
    'nav.helpSubtitle': 'సహాయం కోసం మా ప్రతినిధులను సంప్రదించండి',
    'nav.home': 'హోమ్',
    'nav.login': 'లాగిన్',
    'nav.register': 'ప్రారంభించండి',

    // Header & User Menu
    'header.notifications': 'నోటిఫికేషన్లు',
    'header.markRead': 'అన్నీ చదివినట్లు గుర్తించండి',
    'header.signOut': 'లాగౌట్',
    'header.myProfile': 'నా ప్రొఫైల్',
    'header.settings': 'సెట్టింగ్‌లు',
    'header.new': 'క్రొత్తది',
    'header.noNotifications': 'కొత్త నోటిఫికేషన్లు లేవు',

    // Common Buttons & Labels
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.search': 'వెతకండి...',
    'common.select': 'భాషను ఎంచుకోండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.submit': 'సమర్పించు',
    'common.viewAll': 'అన్నీ చూడండి',
    'common.details': 'వివరాలు',
    'common.status': 'స్థితి',
    'common.date': 'తేదీ',
    'common.action': 'చర్య',
    'common.edit': 'సవరించు',
    'common.delete': 'తొలగించు',
    'common.view': 'చూడండి',
    'common.viewDetails': 'వివరాలు చూడండి',
    'common.back': 'వెనుకకు',
    'common.next': 'తరువాత',
    'common.previous': 'మునుపటి',
    'common.showing': 'చూపిస్తున్నవి',
    'common.to': 'నుండి',
    'common.of': 'మొత్తం',
    'common.items': 'రికార్డులు',
    'common.all': 'అన్నీ',
    'common.clear': 'క్లియర్ చేయండి',
    'common.clearChat': 'చాట్ తొలగించండి',
    'common.copied': 'కాపీ చేయబడింది',
    'common.success': 'విజయం',
    'common.error': 'లోపం సంభవించింది',
    'common.perQuintal': 'క్వింటాల్‌కు',
    'common.acres': 'ఎకరాలు',

    // Dashboard
    'dash.welcome': 'స్వాగతం',
    'dash.subtitle': 'ఈరోజు మీ పొలం సమాచారం',
    'dash.statCrops': 'మొత్తం పంటలు',
    'dash.statRecs': 'నా పంట సూచనలు',
    'dash.statMarket': 'మార్కెట్ ధరలు',
    'dash.statFarmers': 'రైతులు',
    'dash.weatherTitle': 'వాతావరణ ముందస్తు సమాచారం',
    'dash.humidity': 'తేమ',
    'dash.wind': 'గాలి వేగం',
    'dash.chartWeather': 'రాబోయే 7 రోజుల వాతావరణం',
    'dash.chartSeasons': 'సీజన్ ప్రకారం పంటలు',
    'dash.chartYield': 'అంచనా నెలావారీ దిగుబడి',
    'dash.recentRecs': 'ఇటీవలి పంట సూచనలు',
    'dash.noRecs': 'ఇంకా ఎటువంటి పంట సూచనలు లేవు.',
    'dash.getRecBtn': 'పంట సూచనలు పొందండి',
    'dash.match': 'సరిపోలిక',
    'dash.quickActions': 'త్వరిత చర్యలు',

    // Crop Recommendation
    'crop.title': 'పంట సూచనలు',
    'crop.subtitle': 'నేల మరియు వాతావరణానికి అనుగుణంగా స్మార్ట్ సూచనలు',
    'crop.nitrogen': 'నైట్రోజన్ (N)',
    'crop.phosphorus': 'పాస్పరస్ (P)',
    'crop.potassium': 'పొటాషియం (K)',
    'crop.ph': 'pH స్థాయి',
    'crop.rainfall': 'వర్షపాతం (mm)',
    'crop.temperature': 'ఉష్ణోగ్రత (°C)',
    'crop.humidity': 'తేమ (%)',
    'crop.soilType': 'నేల రకం',
    'crop.season': 'సీజన్',
    'crop.getRecommendation': 'సూచనలు పొందండి',
    'crop.results': 'సిఫార్సు చేసిన పంటలు',
    'crop.confidence': 'అనుకూలత స్కోరు',
    'crop.duration': 'పంట కాలపరిమితి',
    'crop.waterReq': 'నీటి అవసరం',
    'crop.yield': 'అంచనా దిగుబడి',
    'crop.marketValue': 'మార్కెట్ విలువ',
    'crop.scientificName': 'శాస్త్రీయ నామం',
    'crop.fertilizerPlan': 'ఎరువుల ప్రణాళిక',

    // Fertilizer
    'fertilizer.title': 'ఎరువుల వివరాలు',
    'fertilizer.subtitle': 'ఎరువు మోతాదును సులభంగా లెక్కించండి',
    'fertilizer.crop': 'పంటను ఎంచుకోండి',
    'fertilizer.area': 'భూమి వైశాల్యం (ఎకరాలు)',
    'fertilizer.currentN': 'ప్రస్తుత నైట్రోజన్ (కేజీ/ఎకరా)',
    'fertilizer.currentP': 'ప్రస్తుత పాస్పరస్ (కేజీ/ఎకరా)',
    'fertilizer.currentK': 'ప్రస్తుత పొటాషియం (కేజీ/ఎకరా)',
    'fertilizer.calculate': 'లెక్కించండి',
    'fertilizer.result': 'సిఫార్సు చేసిన ఎరువులు',
    'fertilizer.urea': 'యూరియా (Urea)',
    'fertilizer.dap': 'డిఏపి (DAP)',
    'fertilizer.mop': 'ఎమ్‌ఓపి (MOP)',
    'fertilizer.organic': 'సేంద్రీయ ఎరువులు',
    'fertilizer.schedule': 'ఎరువుల వేళా పట్టిక',
    'fertilizer.precautions': 'జాగ్రత్తలు',

    // Weather
    'weather.title': 'వాతావరణ సమాచారం',
    'weather.subtitle': 'ప్రాంతీయ వాతావరణ వివరాలు మరియు హెచ్చరికలు',
    'weather.searchLoc': 'ప్రాంతాన్ని వెతకండి...',
    'weather.useMyLocation': 'ప్రస్తుత ప్రాంతాన్ని ఉపయోగించండి',
    'weather.tempMax': 'గరిష్ట ఉష్ణోగ్రత',
    'weather.tempMin': 'కనిష్ట ఉష్ణోగ్రత',
    'weather.rainProb': 'వర్షపు అవకాశం',
    'weather.farmingTip': 'వ్యవసాయ సూచన',
    'weather.rainAlert': 'వర్షం కురిసే అవకాశం ఉంది! మందుల పిచికారీ నిలిపివేయండి.',
    'weather.uvIndex': 'UV సూచిక',
    'weather.pressure': 'పీడనం',
    'weather.visibility': 'దృశ్యమానత',
    'weather.sunrise': 'సూర్యోదయం',
    'weather.sunset': 'సూర్యాస్తమయం',
    'weather.hourlyForecast': 'గంటల వారీ సమాచారం',
    'weather.weeklyForecast': '7 రోజుల సమాచారం',

    // Diseases
    'diseases.title': 'పంట తెగుళ్లు గురింపు',
    'diseases.subtitle': 'పంట తెగుళ్లను గుర్తించి నివారణ చర్యలు పొందండి',
    'diseases.inspectBtn': 'ఫొటోను పరీక్షించండి',
    'diseases.uploadImg': 'ఫొటోను అప్‌లోడ్ చేయండి',
    'diseases.analyzing': 'పంట ఆరోగ్యాన్ని పరీక్షిస్తున్నాము...',
    'diseases.examiningLeaves': 'AI తెగుళ్లను గుర్తిస్తోంది...',
    'diseases.diagnosisTitle': 'AI రోగ నిర్ధారణ నివేదిక',
    'diseases.symptoms': 'లక్షణాలు',
    'diseases.causes': 'కారణాలు',
    'diseases.prevention': 'ముందస్తు జాగ్రత్తలు',
    'diseases.treatment': 'నివారణ చర్యలు',
    'diseases.chemical': 'రసాయన పద్ధతి',
    'diseases.organic': 'సేంద్రీయ పద్ధతి',
    'diseases.viewGuide': 'నివారణ గైడ్ చూడండి',
    'diseases.emptyTitle': 'తెగుళ్ల వివరాలు లేవు',
    'diseases.emptyMsg': 'వరి, టమోటా, పత్తి వంటి పంటలను వెతకండి...',

    // Market Prices
    'market.title': 'మార్కెట్ ధరలు',
    'market.subtitle': 'లైవ్ మార్కెట్ ధరల వివరాలు',
    'market.topGainer': 'నేటి గరిష్ట పెరుగుదల',
    'market.avgRate': 'సగటు మండి ధర',
    'market.activeMandis': 'యాక్టివ్ మండీలు',
    'market.sentiment': 'మార్కెట్ ట్రెండ్',
    'market.commodity': 'పంట రకం',
    'market.marketName': 'మార్కెట్ / మండి',
    'market.minPrice': 'కనిష్ట ధర',
    'market.maxPrice': 'గరిష్ట ధర',
    'market.modalPrice': 'సగటు ధర',
    'market.prevPrice': 'మునుపటి ధర',
    'market.trend24h': '24 గంటల ట్రెండ్',
    'market.district': 'జిల్లా',
    'market.filterCrop': 'పంట ద్వారా వెతకండి',
    'market.allMandis': 'అన్ని మార్కెట్లు',
    'market.bullish': 'ధర పెరుగుదల',
    'market.bearish': 'ధర తగ్గుదల',
    'market.stable': 'స్థిరంగా ఉంది',
    'market.emptyTitle': 'మార్కెట్ ధరలు కనుగొనబడలేదు',
    'market.emptyMsg': 'వరి, టమోటా, ఉల్లిపాయ, పత్తి మొదలైనవి వెతకండి...',

    // Image Gallery
    'gallery.title': 'చిత్ర గ్యాలరీ',
    'gallery.subtitle': 'పంటల ఫోటోలు మరియు తెగుళ్ల చిత్రాలు',
    'gallery.cropsTab': 'పంటలు',
    'gallery.diseasesTab': 'తెగుళ్లు',
    'gallery.searchPlaceholder': 'పంట లేదా తెగులు పేరు వెతకండి...',
    'gallery.itemsCount': 'చిత్రాలు',
    'gallery.cereal': 'ధాన్యాలు',
    'gallery.vegetable': 'కూరగాయలు',
    'gallery.fruit': 'పండ్లు',
    'gallery.cashCrop': 'వాణిజ్య పంటలు',
    'gallery.oilseed': 'నూనెగింజలు',
    'gallery.spice': 'మసాలా దినుసులు',
    'gallery.plantation': 'తోట పంటలు',
    'gallery.bestSeason': 'అనుకూల సీజన్',
    'gallery.affects': 'ప్రభావిత పంట',
    'gallery.symptoms': 'లక్షణాలు',

    // AI Assistant
    'ai.title': 'స్మార్ట్ AI వ్యవసాయ సహాయకుడు',
    'ai.subtitle': 'పంటలు, నేల, ఎరువులు మరియు వాతావరణం గురించి ఏమైనా అడగండి',
    'ai.inputPlaceholder': 'మీ ప్రశ్నను టైప్ చేయండి...',
    'ai.send': 'పంపండి',
    'ai.prompt1': 'ఎర్ర నేలలో వేయడానికి అనుకూలమైన పంట ఏది?',
    'ai.prompt2': 'వరి కాండం తొలుచు పురుగు నివారణ ఎలా?',
    'ai.prompt3': 'టమాటో ప్రస్తుత మార్కెట్ ధర ఎంత?',
    'ai.disclaimer': 'AI సూచనలు వ్యవసాయ సమాచారం ఆధారంగా ఇవ్వబడ్డాయి.',
    'ai.listening': 'వింటున్నాను... మాట్లాడండి',
    'ai.voiceError': 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్పుట్ పనిచేయదు',
    'ai.analyzing': 'వ్యవసాయ సమాచారం పరిశీలిస్తున్నాము...',
    'ai.readAloud': 'వినండి',
    'ai.copyAnswer': 'సమాధానం కాపీ చేయండి',
    'ai.pillPaddy': '🌾 వరి సాగు గైడ్',
    'ai.pillTomato': '🍅 టమోటా సంరక్షణ',
    'ai.pillFertilizer': '🧪 NPK ఎరువులు',
    'ai.pillPest': '🌿 సేంద్రీయ నివారణ',
    'ai.pillSchemes': '🏛️ ప్రభుత్వ పథకాలు',
    'ai.pillMandi': '📈 మార్కెట్ సూచనలు',

    // Reports
    'reports.title': 'వ్యవసాయ నివేదికలు',
    'reports.subtitle': 'నివేదికలను డౌన్‌లోడ్ చేసుకోండి',
    'reports.downloadPdf': 'PDF నివేదిక పొందండి',
    'reports.summary': 'సారాంశం',
    'reports.soilHealth': 'నేల ఆరోగ్య సూచిక',
    'reports.farmOverview': 'పొలం సమాచారం',
    'reports.cropHistory': 'సూచనల చరిత్ర',

    // Farm Details
    'farm.title': 'పొలం & నేల వివరాలు',
    'farm.subtitle': 'నేల పోషకాలు మరియు నీటి పారుదల పద్ధతులు',
    'farm.soilType': 'నేల రకం',
    'farm.soilPh': 'pH స్థాయి (1-14)',
    'farm.nitrogen': 'నైట్రోజన్ (N)',
    'farm.phosphorus': 'పాస్పరస్ (P)',
    'farm.potassium': 'పొటాషియం (K)',
    'farm.rainfall': 'వర్షపాతం (mm)',
    'farm.temperature': 'ఉష్ణోగ్రత (°C)',
    'farm.humidity': 'తేమ శాతం (%)',
    'farm.waterAvailability': 'నీటి వనరులు',
    'farm.irrigationMethod': 'సాగునీటి విధానం',
    'farm.season': 'ప్రస్తుత సీజన్',
    'farm.saveSuccess': 'పొలం వివరాలు విజయవంతంగా సేవ్ అయ్యాయి!',

    // Profile
    'profile.title': 'రైతు ప్రొఫైల్',
    'profile.subtitle': 'మీ వివరాలు మరియు పొలం వివరాలు నిర్వహించండి',
    'profile.name': 'పూర్తి పేరు',
    'profile.phone': 'ఫోన్ నంబర్',
    'profile.state': 'రాష్ట్రం',
    'profile.district': 'జిల్లా',
    'profile.village': 'గ్రామం / ఊరు',
    'profile.landSize': 'మొత్తం వైశాల్యం (ఎకరాలు)',
    'profile.updateProfile': 'ప్రొఫైల్ నవీకరించండి',
    'profile.role': 'ఖాతా రకం',
    'profile.memberSince': 'చేరిన తేదీ',

    // Settings
    'settings.title': 'సెట్టింగ్‌లు',
    'settings.subtitle': 'మీ ఖాతా, డిస్‌ప్లే మరియు భాషా ప్రాధాన్యతలు',
    'settings.display': 'డిస్‌ప్లే మరియు థీమ్',
    'settings.mode': 'లైట్ / డార్క్ మోడ్',
    'settings.modeDesc': 'లైట్ మరియు డార్క్ మోడ్ మధ్య మారండి',
    'settings.language': 'భాష (Language)',
    'settings.selectLanguage': 'యాప్ కోసం మీ భాషను ఎంచుకోండి',
    'settings.notifications': 'నోటిఫికేషన్లు మరియు అలర్ట్‌లు',
    'settings.pushNotif': 'పుష్ నోటిఫికేషన్లు',
    'settings.pushDesc': 'వాతావరణం & మార్కెట్ ధరల అలర్ట్‌లు పొందండి',
    'settings.emailNotif': 'ఇమెయిల్ సలహాలు',
    'settings.emailDesc': 'వారాంతపు నివేదికలను ఇమెయిల్ ద్వారా పొందండి',
    'settings.security': 'భద్రత',
    'settings.changePassword': 'పాస్‌వర్డ్ మార్చండి',

    // Landing Page
    'landing.heroTitle': 'రైతుల కోసం స్మార్ట్ వ్యవసాయ సలహా వేదిక',
    'landing.heroSubtitle': 'AI సూచనలు, నేల విశ్లేషణ, తెగుళ్ల గుర్తింపు మరియు లైవ్ మార్కెట్ ధరలతో అధిక దిగుబడి మరియు లాభాలు.',
    'landing.getStarted': 'ఉచితంగా ప్రారంభించండి',
    'landing.exploreFeatures': 'ఫీచర్లు చూడండి',
    'landing.feature1Title': 'స్మార్ట్ పంట ఎంపిక',
    'landing.feature1Desc': 'మీ నేల, పోషకాలు, వర్షపాతానికి అనుగుణంగా సరైన పంటల ఎంపిక.',
    'landing.feature2Title': 'లైవ్ మార్కెట్ ధరలు',
    'landing.feature2Desc': '100+ వ్యవసాయ మార్కెట్ల ధరలు తెలుసుకుని సరైన సమయంలో అమ్మండి.',
    'landing.feature3Title': 'AI తెగుళ్ల డాక్టర్',
    'landing.feature3Desc': 'ఫొటో తీసి నివారణ పద్ధతులు మరియు సేంద్రీయ పరిష్కారాలు పొందండి.',
    'landing.feature4Title': 'ఎరువుల కాలిక్యులేటర్',
    'landing.feature4Desc': 'యూరియా, డీఏపీ, పొటాష్ సరియైన మోతాదు లెక్కింపు.',
    'landing.feature5Title': 'ఖచ్చితమైన వాతావరణం',
    'landing.feature5Desc': '7 రోజుల వర్షపాతం మరియు ఉష్ణోగ్రత సూచనలు.',
    'landing.feature6Title': 'బహుభాషా AI అసిస్టెంట్',
    'landing.feature6Desc': 'తెలుగు, తమిళం, హిందీ, ఇంగ్లీష్ భాషలలో వాయిస్ సదుపాయం.',
    'landing.statsFarmers': '10,000+ రైతుల సంతృప్తి',
    'landing.statsAccuracy': '98% ఖచ్చితమైన ఫలితాలు',
    'landing.statsMandis': '50+ ప్రత్యక్ష మార్కెట్లు',

    // About & Contact
    'about.title': 'CropAdvisory గురించి',
    'about.subtitle': 'రైతుల సంక్షేమం కోసం ఆధునిక వ్యవసాయ విజ్ఞానం',
    'about.missionTitle': 'మా లక్ష్యం',
    'about.missionDesc': 'ప్రతి రైతుకు ఆధునిక వ్యవసాయ విజ్ఞానాన్ని సులభంగా అందించడం.',
    'contact.title': 'సహాయ కేంద్రం',
    'contact.subtitle': 'ఏవైనా ప్రశ్నలు ఉన్నాయా? మేము మీకు 24/7 అందుబాటులో ఉంటాము.',
    'contact.name': 'మీ పేరు',
    'contact.email': 'మీ ఇమెయిల్',
    'contact.message': 'మీ సందేశం',
    'contact.sendMsg': 'సందేశం పంపండి',
    'contact.sentSuccess': 'మీ సందేశం చేరింది. త్వరలో స్పందిస్తాము!',

    // Footer
    'footer.tagline': 'స్మార్ట్ వ్యవసాయ మరియు పంట సలహా వ్యవస్థ',
    'footer.rights': 'సర్వహక్కులు రక్షించబడ్డాయి. రైతుల సేవలో.',
    'footer.quickLinks': 'ముఖ్య లింకులు',
    'footer.tools': 'సలహా సాధనాలు',
    'footer.legal': 'నిబంధనలు',
  },

  es: {
    // Navigation
    'nav.dashboard': 'Panel de Control',
    'nav.profile': 'Perfil',
    'nav.farmDetails': 'Detalles de Granja',
    'nav.cropSuggestion': 'Sugerencia de Cultivo',
    'nav.fertilizer': 'Fertilizante',
    'nav.weather': 'Clima',
    'nav.diseases': 'Enfermedades',
    'nav.gallery': 'Galería de Imágenes',
    'nav.marketPrices': 'Precios del Mercado',
    'nav.aiAssistant': 'Asistente Inteligente',
    'nav.reports': 'Reportes',
    'nav.settings': 'Configuración',
    'nav.adminTools': 'Herramientas de Admin',
    'nav.contactUs': 'Contáctenos',
    'nav.about': 'Sobre Nosotros',
    'nav.needHelp': '¿Necesita Ayuda?',
    'nav.helpSubtitle': 'Contacte a nuestro equipo de soporte',
    'nav.home': 'Inicio',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Comenzar',

    // Header & User Menu
    'header.notifications': 'Notificaciones',
    'header.markRead': 'Marcar todo como leído',
    'header.signOut': 'Cerrar Sesión',
    'header.myProfile': 'Mi Perfil',
    'header.settings': 'Configuración',
    'header.new': 'nuevo',
    'header.noNotifications': 'No hay nuevas notificaciones',

    // Common Buttons & Labels
    'common.save': 'Guardar Cambios',
    'common.cancel': 'Cancelar',
    'common.search': 'Buscar...',
    'common.select': 'Seleccionar Idioma',
    'common.loading': 'Cargando...',
    'common.submit': 'Enviar',
    'common.viewAll': 'Ver Todo',
    'common.details': 'Detalles',
    'common.status': 'Estado',
    'common.date': 'Fecha',
    'common.action': 'Acción',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.viewDetails': 'Ver Detalles',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.showing': 'Mostrando',
    'common.to': 'a',
    'common.of': 'de',
    'common.items': 'elementos',
    'common.all': 'Todos',
    'common.clear': 'Limpiar',
    'common.clearChat': 'Limpiar Chat',
    'common.copied': 'Copiado al portapapeles',
    'common.success': 'Éxito',
    'common.error': 'Ocurrió un error',
    'common.perQuintal': 'por quintal',
    'common.acres': 'acres',

    // Dashboard
    'dash.welcome': 'Bienvenido',
    'dash.subtitle': 'Esto es lo que sucede hoy en su granja',
    'dash.statCrops': 'Total de Cultivos',
    'dash.statRecs': 'Mis Sugerencias',
    'dash.statMarket': 'Precios de Mercado',
    'dash.statFarmers': 'Agricultores',
    'dash.weatherTitle': 'Pronóstico del Tiempo',
    'dash.humidity': 'Humedad',
    'dash.wind': 'Viento',
    'dash.chartWeather': 'Clima para los Próximos 7 Días',
    'dash.chartSeasons': 'Cultivos por Temporada',
    'dash.chartYield': 'Cosecha Mensual Esperada',
    'dash.recentRecs': 'Sugerencias Recientes',
    'dash.noRecs': 'Aún no hay sugerencias.',
    'dash.getRecBtn': 'Obtener Sugerencias',
    'dash.match': 'coincidencia',
    'dash.quickActions': 'Acciones Rápidas',

    // Crop Recommendation
    'crop.title': 'Sugerencia de Cultivo',
    'crop.subtitle': 'Obtenga sugerencias adaptadas a su suelo y clima',
    'crop.nitrogen': 'Nitrógeno (N)',
    'crop.phosphorus': 'Fósforo (P)',
    'crop.potassium': 'Potasio (K)',
    'crop.ph': 'Nivel de pH',
    'crop.rainfall': 'Precipitación (mm)',
    'crop.temperature': 'Temperatura (°C)',
    'crop.humidity': 'Humedad (%)',
    'crop.soilType': 'Tipo de Suelo',
    'crop.season': 'Temporada',
    'crop.getRecommendation': 'Obtener Recomendación',
    'crop.results': 'Cultivos Recomendados',
    'crop.confidence': 'Puntaje de Idoneidad',
    'crop.duration': 'Duración del Crecimiento',
    'crop.waterReq': 'Requerimiento de Agua',
    'crop.yield': 'Rendimiento Esperado',
    'crop.marketValue': 'Valor de Mercado',
    'crop.scientificName': 'Nombre Científico',
    'crop.fertilizerPlan': 'Plan de Fertilización',

    // Fertilizer
    'fertilizer.title': 'Asesoría de Fertilizantes',
    'fertilizer.subtitle': 'Calcule la dosis exacta para un rendimiento óptimo',
    'fertilizer.crop': 'Seleccionar Cultivo',
    'fertilizer.area': 'Área de Tierra (Acres)',
    'fertilizer.currentN': 'Nitrógeno Actual (kg/acre)',
    'fertilizer.currentP': 'Fósforo Actual (kg/acre)',
    'fertilizer.currentK': 'Potasio Actual (kg/acre)',
    'fertilizer.calculate': 'Calcular Dosis',
    'fertilizer.result': 'Fertilizantes Recomendados',
    'fertilizer.urea': 'Urea (46% N)',
    'fertilizer.dap': 'DAP (18:46:0)',
    'fertilizer.mop': 'MOP (60% K)',
    'fertilizer.organic': 'Alternativas Orgánicas',
    'fertilizer.schedule': 'Calendario de Aplicación',
    'fertilizer.precautions': 'Precauciones y Seguridad',

    // Weather
    'weather.title': 'Asesoría Meteorológica',
    'weather.subtitle': 'Pronósticos locales y alertas agrícolas',
    'weather.searchLoc': 'Buscar ubicación o distrito...',
    'weather.useMyLocation': 'Usar Ubicación Actual',
    'weather.tempMax': 'Temp Máxima',
    'weather.tempMin': 'Temp Mínima',
    'weather.rainProb': 'Precipitación',
    'weather.farmingTip': 'Consejo Agrícola',
    'weather.rainAlert': '¡Lluvia esperada! Posponga la aplicación de pesticidas.',
    'weather.uvIndex': 'Índice UV',
    'weather.pressure': 'Presión',
    'weather.visibility': 'Visibilidad',
    'weather.sunrise': 'Amanecer',
    'weather.sunset': 'Atardecer',
    'weather.hourlyForecast': 'Pronóstico por Hora',
    'weather.weeklyForecast': 'Pronóstico de 7 Días',

    // Diseases
    'diseases.title': 'Identificación de Plagas y Enfermedades',
    'diseases.subtitle': 'Identifique enfermedades y obtenga tratamientos',
    'diseases.inspectBtn': 'Inspeccionar Foto del Cultivo',
    'diseases.uploadImg': 'Subir Foto del Cultivo',
    'diseases.analyzing': 'Analizando salud del cultivo...',
    'diseases.examiningLeaves': 'La IA está examinando las hojas en busca de patógenos...',
    'diseases.diagnosisTitle': 'Informe de Diagnóstico IA',
    'diseases.symptoms': 'Síntomas Observados',
    'diseases.causes': 'Causas Principales',
    'diseases.prevention': 'Pasos de Prevención',
    'diseases.treatment': 'Tratamiento y Control',
    'diseases.chemical': 'Tratamiento Químico',
    'diseases.organic': 'Solución Orgánica',
    'diseases.viewGuide': 'Ver Guía de Tratamiento',
    'diseases.emptyTitle': 'No se encontraron enfermedades',
    'diseases.emptyMsg': 'Busque cultivos como Arroz, Tomate, Trigo, Plátano, Algodón...',

    // Market Prices
    'market.title': 'Precios de Mercado y Tendencias',
    'market.subtitle': 'Precios en vivo y análisis de mercado',
    'market.topGainer': 'Mayor Aumento Hoy',
    'market.avgRate': 'Precio Promedio del Mercado',
    'market.activeMandis': 'Mercados Activos',
    'market.sentiment': 'Sentimiento del Mercado',
    'market.commodity': 'Producto',
    'market.marketName': 'Mercado',
    'market.minPrice': 'Precio Mín',
    'market.maxPrice': 'Precio Máx',
    'market.modalPrice': 'Precio Promedio',
    'market.prevPrice': 'Precio Anterior',
    'market.trend24h': 'Tendencia 24h',
    'market.district': 'Distrito',
    'market.filterCrop': 'Filtrar por Cultivo',
    'market.allMandis': 'Todos los Mercados',
    'market.bullish': 'En Alza',
    'market.bearish': 'En Baja',
    'market.stable': 'Estable',
    'market.emptyTitle': 'No se encontraron precios',
    'market.emptyMsg': 'Busque Arroz, Tomate, Cebolla, Algodón, Chile...',

    // Image Gallery
    'gallery.title': 'Galería de Imágenes',
    'gallery.subtitle': 'Fotos hermosas de cultivos e identificación de enfermedades',
    'gallery.cropsTab': 'Cultivos',
    'gallery.diseasesTab': 'Enfermedades',
    'gallery.searchPlaceholder': 'Buscar cultivos o enfermedades por nombre...',
    'gallery.itemsCount': 'imágenes',
    'gallery.cereal': 'Cereales',
    'gallery.vegetable': 'Verduras',
    'gallery.fruit': 'Frutas',
    'gallery.cashCrop': 'Cultivos Comerciales',
    'gallery.oilseed': 'Oleaginosas',
    'gallery.spice': 'Especias',
    'gallery.plantation': 'Plantaciones',
    'gallery.bestSeason': 'Mejor Temporada',
    'gallery.affects': 'Afecta a',
    'gallery.symptoms': 'Síntomas',

    // AI Assistant
    'ai.title': 'Asistente Agrícola Inteligente AI',
    'ai.subtitle': 'Pregunte sobre cultivos, suelo, plagas, subsidios y precios de mercado',
    'ai.inputPlaceholder': 'Haga su pregunta agrícola en cualquier idioma...',
    'ai.send': 'Enviar',
    'ai.prompt1': '¿Qué cultivo es mejor para suelo rojo?',
    'ai.prompt2': '¿Cómo controlar las plagas del arroz de forma natural?',
    'ai.prompt3': '¿Cuál es la tendencia actual del mercado de tomate?',
    'ai.disclaimer': 'Las sugerencias de IA se basan en datos agrícolas.',
    'ai.listening': 'Escuchando... Diga su pregunta',
    'ai.voiceError': 'La entrada de voz no es compatible en este navegador',
    'ai.analyzing': 'Analizando datos agrícolas...',
    'ai.readAloud': 'Leer en voz alta',
    'ai.copyAnswer': 'Copiar respuesta',
    'ai.pillPaddy': '🌾 Cultivo de Arroz',
    'ai.pillTomato': '🍅 Cuidados del Tomate',
    'ai.pillFertilizer': '🧪 Fertilizantes NPK',
    'ai.pillPest': '🌿 Control Orgánico',
    'ai.pillSchemes': '🏛️ Subsidios Agrícolas',
    'ai.pillMandi': '📈 Precios y Ventas',

    // Reports
    'reports.title': 'Informes de Asesoría Agrícola',
    'reports.subtitle': 'Descargue y vea informes de granja',
    'reports.downloadPdf': 'Descargar Informe PDF',
    'reports.summary': 'Resumen de Temporada',
    'reports.soilHealth': 'Índice de Salud del Suelo',
    'reports.farmOverview': 'Resumen de Granja',
    'reports.cropHistory': 'Historial de Recomendaciones',

    // Farm Details
    'farm.title': 'Detalles de Granja y Suelo',
    'farm.subtitle': 'Gestione parámetros de suelo, nutrientes y riego',
    'farm.soilType': 'Tipo de Suelo',
    'farm.soilPh': 'pH del Suelo (1-14)',
    'farm.nitrogen': 'Nitrógeno Disponible (N)',
    'farm.phosphorus': 'Fósforo Disponible (P)',
    'farm.potassium': 'Potasio Disponible (K)',
    'farm.rainfall': 'Precipitación Promedio (mm)',
    'farm.temperature': 'Temperatura Promedio (°C)',
    'farm.humidity': 'Humedad Promedio (%)',
    'farm.waterAvailability': 'Disponibilidad de Agua',
    'farm.irrigationMethod': 'Método de Riego',
    'farm.season': 'Temporada Actual',
    'farm.saveSuccess': '¡Detalles de la granja guardados exitosamente!',

    // Profile
    'profile.title': 'Perfil del Agricultor',
    'profile.subtitle': 'Gestione sus datos personales y de granja',
    'profile.name': 'Nombre Completo',
    'profile.phone': 'Número de Teléfono',
    'profile.state': 'Estado / Región',
    'profile.district': 'Distrito',
    'profile.village': 'Pueblo / Ciudad',
    'profile.landSize': 'Área Total de Tierra (Acres)',
    'profile.updateProfile': 'Actualizar Perfil',
    'profile.role': 'Rol de Cuenta',
    'profile.memberSince': 'Miembro Desde',

    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestione su cuenta, apariencia e idioma',
    'settings.display': 'Apariencia y Tema',
    'settings.mode': 'Modo Claro / Oscuro',
    'settings.modeDesc': 'Cambiar entre modo claro y oscuro',
    'settings.language': 'Idioma (Language)',
    'settings.selectLanguage': 'Seleccione su idioma preferido para toda la app',
    'settings.notifications': 'Notificaciones y Alertas',
    'settings.pushNotif': 'Notificaciones Push',
    'settings.pushDesc': 'Recibir alertas de clima y precios de mercado al instante',
    'settings.emailNotif': 'Asesoría por Correo',
    'settings.emailDesc': 'Recibir informes semanales por correo',
    'settings.security': 'Seguridad',
    'settings.changePassword': 'Cambiar Contraseña',

    // Landing Page
    'landing.heroTitle': 'Asesoría Agrícola Inteligente para Agricultores',
    'landing.heroSubtitle': 'Potenciando a los agricultores con sugerencias de cultivos basadas en IA, análisis de suelo, detección de plagas y precios de mercado en vivo.',
    'landing.getStarted': 'Comenzar Gratis',
    'landing.exploreFeatures': 'Explorar Funciones',
    'landing.feature1Title': 'Sugerencias Inteligentes',
    'landing.feature1Desc': 'Recomendaciones personalizadas según los nutrientes de su suelo, pH y clima.',
    'landing.feature2Title': 'Precios de Mercado en Vivo',
    'landing.feature2Desc': 'Monitoree precios en mercados agrícolas para vender al mejor precio.',
    'landing.feature3Title': 'Doctor de Cultivos con IA',
    'landing.feature3Desc': 'Suba fotos de plantas para diagnóstico instantáneo de patógenos y soluciones orgánicas.',
    'landing.feature4Title': 'Calculadora de Fertilizantes (NPK)',
    'landing.feature4Desc': 'Dosis precisa de Urea, DAP, Potasio y compost orgánico por acre.',
    'landing.feature5Title': 'Alertas Meteorológicas Precisas',
    'landing.feature5Desc': 'Pronósticos de 7 días de lluvia y temperatura adaptados para agricultura.',
    'landing.feature6Title': 'Asistente Multilingüe con IA',
    'landing.feature6Desc': 'Asistente de voz disponible en español, inglés, tamil, hindi y telugu.',
    'landing.statsFarmers': '10,000+ Agricultores Asistidos',
    'landing.statsAccuracy': '98% de Precisión en Recomendaciones',
    'landing.statsMandis': '50+ Mercados Agrícolas',

    // About & Contact
    'about.title': 'Acerca de CropAdvisory',
    'about.subtitle': 'Ciencia agrícola digital para la prosperidad del agricultor',
    'about.missionTitle': 'Nuestra Misión',
    'about.missionDesc': 'Democratizar la ciencia agrícola avanzada y los datos de mercado para cada agricultor.',
    'contact.title': 'Contacto de Soporte',
    'contact.subtitle': '¿Tiene preguntas? Nuestro equipo está disponible 24/7.',
    'contact.name': 'Su Nombre',
    'contact.email': 'Su Correo Electrónico',
    'contact.message': 'Su Mensaje',
    'contact.sendMsg': 'Enviar Mensaje',
    'contact.sentSuccess': '¡Su mensaje ha sido enviado! Responderemos pronto.',

    // Footer
    'footer.tagline': 'Sistema Inteligente de Asesoría Agrícola',
    'footer.rights': 'Todos los derechos reservados. Desarrollado con pasión para los agricultores.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.tools': 'Herramientas',
    'footer.legal': 'Privacidad y Términos',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguageOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('app_language');
    if (saved && (saved === 'en' || saved === 'ta' || saved === 'hi' || saved === 'te' || saved === 'es')) {
      return saved as LanguageCode;
    }
    return 'en';
  });

  const applyAutoTranslation = (lang: LanguageCode) => {
    try {
      const gtCombo = document.querySelector('.goog-te-combo') as HTMLSelectElement | null;
      if (gtCombo) {
        gtCombo.value = lang;
        gtCombo.dispatchEvent(new Event('change'));
      }
      document.cookie = `googtrans=/en/${lang}; path=/;`;
      document.cookie = `googtrans=/en/${lang}; path=/; domain=${window.location.hostname}`;
    } catch {
      // Ignore fallback errors
    }
  };

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    applyAutoTranslation(lang);
  };

  React.useEffect(() => {
    if (language && language !== 'en') {
      const timer = setTimeout(() => applyAutoTranslation(language), 800);
      return () => clearTimeout(timer);
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const currentLanguageOption = SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageOption }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
