-- Seed Master Data for Agriculture Advisory System
-- Populates market_prices, crops, fertilizers, and diseases if empty

-- 1. SEED MARKET PRICES
INSERT INTO market_prices (crop_name, market_name, current_price, previous_price, price_trend) VALUES
('Paddy (Basmati)', 'Khanna Mandi (Punjab)', 3850, 3650, 'up'),
('Paddy (Common)', 'Thanjavur Mandi (TN)', 2350, 2200, 'up'),
('Wheat (Sharbati)', 'Indore Mandi (MP)', 2850, 2750, 'up'),
('Wheat (Kalyan)', 'Karnal Mandi (Haryana)', 2420, 2450, 'down'),
('Tomato', 'Dindigul Mandi (TN)', 2800, 2100, 'up'),
('Tomato (Hybrid)', 'Kolar Mandi (Karnataka)', 2600, 2900, 'down'),
('Onion (Red)', 'Lasalgaon Mandi (Nashik)', 1850, 1600, 'up'),
('Onion (White)', 'Mahuvam Mandi (Gujarat)', 1750, 1800, 'down'),
('Potato (Jyoti)', 'Agra Mandi (UP)', 1450, 1380, 'up'),
('Potato (Chipsona)', 'Hooghly Mandi (WB)', 1600, 1650, 'down'),
('Cotton (Medium Staple)', 'Rajkot Mandi (Gujarat)', 7250, 7100, 'up'),
('Cotton (Long Staple)', 'Warangal Mandi (Telangana)', 7800, 7950, 'down'),
('Sugarcane', 'Coimbatore Mandi (TN)', 340, 320, 'up'),
('Chilli (Teja Red)', 'Guntur Mandi (AP)', 18500, 17200, 'up'),
('Maize (Yellow)', 'Davangere Mandi (Karnataka)', 2250, 2180, 'up'),
('Soybean (Yellow)', 'Ujjain Mandi (MP)', 4650, 4800, 'down'),
('Groundnut (Pod)', 'Bikaner Mandi (Rajasthan)', 6300, 6150, 'up'),
('Banana (Robusta)', 'Theni Mandi (TN)', 1950, 1750, 'up'),
('Turmeric (Finger)', 'Erode Mandi (TN)', 14200, 13500, 'up'),
('Mustard', 'Jaipur Mandi (Rajasthan)', 5450, 5300, 'up'),
('Garlic', 'Mandsaur Mandi (MP)', 12500, 13200, 'down'),
('Ginger (Fresh)', 'Wayanad Mandi (Kerala)', 6800, 6400, 'up')
ON CONFLICT DO NOTHING;

-- 2. SEED CROPS MASTER DATA
INSERT INTO crops (crop_name, scientific_name, soil_type, suitable_season, water_requirement, temperature_range, rainfall_range, fertilizer, growth_duration, expected_yield, market_value, image_url) VALUES
('Paddy', 'Oryza sativa', 'Clayey / Loamy', 'Kharif', 'High (1200-1500 mm)', '22-32°C', '1000-1500 mm', 'Urea: 50kg, DAP: 50kg, MOP: 25kg', '120-140 days', '4-5 tons/acre', 'High', 'https://images.pexels.com/photos/247599/pexels-photo-247599.jpeg?auto=compress&cs=tinysrgb&w=600'),
('Wheat', 'Triticum aestivum', 'Loamy / Clay Loam', 'Rabi', 'Medium (450-650 mm)', '15-25°C', '500-750 mm', 'Urea: 60kg, DAP: 55kg, MOP: 20kg', '110-130 days', '3-4 tons/acre', 'High', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80'),
('Cotton', 'Gossypium hirsutum', 'Black / Regur Soil', 'Kharif', 'Medium (600-800 mm)', '21-30°C', '600-1000 mm', 'NPK: 60:30:30 kg/acre', '150-180 days', '1.5-2.5 tons/acre', 'Very High', 'https://images.unsplash.com/photo-1594488555776-8809ff44f24b?w=600&auto=format&fit=crop&q=80'),
('Tomato', 'Solanum lycopersicum', 'Red Loam / Sandy Loam', 'All Season', 'Medium (400-600 mm)', '18-28°C', '500-700 mm', 'FYM: 10t, DAP: 40kg, Potash: 30kg', '90-110 days', '15-20 tons/acre', 'High', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80'),
('Onion', 'Allium cepa', 'Sandy Loam', 'Rabi / Kharif', 'Medium (350-550 mm)', '15-28°C', '400-600 mm', 'NPK: 40:20:30 kg/acre', '100-120 days', '10-15 tons/acre', 'High', 'https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=80'),
('Sugarcane', 'Saccharum officinarum', 'Deep Rich Loamy', 'All Season', 'High (1500-2500 mm)', '20-35°C', '1100-1500 mm', 'Urea: 100kg, SSP: 125kg, MOP: 50kg', '300-365 days', '40-50 tons/acre', 'Very High', 'https://images.unsplash.com/photo-1598112972019-91e1162b80f7?w=600&auto=format&fit=crop&q=80'),
('Maize', 'Zea mays', 'Well-drained Loam', 'Kharif / Rabi', 'Medium (500-750 mm)', '18-30°C', '600-900 mm', 'Urea: 50kg, DAP: 45kg, MOP: 25kg', '90-110 days', '3-4 tons/acre', 'Medium', 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&auto=format&fit=crop&q=80'),
('Chilli', 'Capsicum annuum', 'Black / Red Loam', 'Kharif', 'Low-Medium (400-600 mm)', '20-30°C', '500-800 mm', 'NPK: 50:25:25 kg/acre', '120-150 days', '2-3 tons dry/acre', 'Very High', 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80')
ON CONFLICT DO NOTHING;

-- 3. SEED FERTILIZERS MASTER DATA
INSERT INTO fertilizers (fertilizer_name, soil_condition, quantity, application_method, precautions) VALUES
('Urea (46% N)', 'Nitrogen deficient soils, all soil types', '50-100 kg/acre in 2-3 split doses', 'Broadcast or side dressing near root zone', 'Do not apply in direct water logging; mix with neem cake for slow release'),
('DAP (Di-Ammonium Phosphate 18:46:0)', 'Phosphorus deficient, neutral to alkaline soils', '40-50 kg/acre as basal dose', 'Soil placement at sowing or transplanting', 'Always apply before sowing directly into furrow near seeds'),
('MOP (Muriate of Potash 60% K2O)', 'Sandy and light textured soils', '25-40 kg/acre in split doses', 'Basal and top dressing at flowering', 'Avoid excess in saline soils; use SOP for chlorine-sensitive crops'),
('Single Super Phosphate (SSP 16% P, 11% S)', 'Sulphur & Phosphorus deficient soils', '100-150 kg/acre basal', 'Soil incorporation during field preparation', 'Best suited for oilseeds (Groundnut, Mustard) and pulses'),
('Vermicompost (Organic)', 'Low organic carbon soils (< 0.5% OC)', '2-3 tons/acre', 'Broadcast and mix during primary ploughing', 'Keep moist and protect from direct harsh sunlight'),
('Zinc Sulphate (21% Zn)', 'Zinc deficient, intensive cereal cropped soils', '10 kg/acre once in 2 seasons', 'Basal soil application', 'Never mix directly with phosphate fertilizers like DAP/SSP')
ON CONFLICT DO NOTHING;

-- 4. SEED DISEASES MASTER DATA
INSERT INTO diseases (crop_name, disease_name, symptoms, causes, prevention, treatment, organic_solution, image_url, season) VALUES
('Paddy', 'Blast Disease', 'Spindle-shaped diamond spots with grey center on leaves; dark neck rot', 'Fungus Magnaporthe oryzae, high humidity (>90%)', 'Avoid excess nitrogen fertilizer, use resistant varieties', 'Spray Tricyclazole 75 WP @ 120g/acre or Isoprothiolane 40 EC', 'Spray Pseudomonas fluorescens @ 1 kg/acre or 5% neem seed kernel extract', 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Paddy', 'Stem Borer', 'Dead heart in vegetative stage; White earhead with chaffy grains in reproductive stage', 'Scirpophaga incertulas larvae boring into central shoot', 'Clip seedling tips before transplanting, install 5 pheromone traps/acre', 'Apply Chlorantraniliprole 18.5 SC @ 60 ml/acre or Cartap hydrochloride 4G @ 10 kg/acre', 'Release Trichogramma egg parasitoids @ 60,000/acre; spray 5% Neem oil', 'https://images.unsplash.com/photo-1532451372562-b9e07fb293c0?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Tomato', 'Leaf Curl Virus', 'Severe curling, puckering of leaves, stunting of plants with bushy appearance', 'Tomato leaf curl virus transmitted by Whitefly (Bemisia tabaci)', 'Install 15 yellow sticky traps/acre, use barrier crops like maize/sorghum', 'Spray Acetamiprid 20 SP @ 50g/acre or Imidacloprid 17.8 SL @ 60ml/acre', 'Spray Neem oil (10,000 ppm) @ 5ml/L + garlic extract every 10 days', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Cotton', 'Pink Bollworm', 'Rosetted flowers, bore holes in bolls with pink larvae feeding on seeds and lint', 'Pectinophora gossypiella larvae', 'Crop rotation, destroy crop residue, install 8-10 pheromone traps/acre', 'Spray Emamectin benzoate 5 SG @ 100g/acre or Spinosad 45 SC @ 75ml/acre', 'Spray Agniastra or Neem seed kernel extract 5%; release Trichogramma wasps', 'https://images.unsplash.com/photo-1628172908865-c70e28f28ab5?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Wheat', 'Yellow Rust (Stripe Rust)', 'Yellow pustules arranged in linear stripes on leaf surface, powder rubs off on fingers', 'Fungus Puccinia striiformis, cool temperatures (10-15°C) and dew', 'Early sowing, use rust-resistant cultivars (HD 2967, PBW 550)', 'Spray Propiconazole 25 EC @ 200ml/acre in 200L water', 'Spray sour buttermilk (5L in 100L water) or Trichoderma viride', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80', 'Rabi'),
('Sugarcane', 'Red Rot (Colletotrichum falcatum)', 'Yellowing of upper leaves, red lesions on the midrib, sour alcohol smell when cane is split.', 'Fungus spreading through infected setts and soil.', 'Use healthy setts, practice crop rotation, ensure good field drainage.', 'Sett treatment with Carbendazim 50 WP @ 1g/litre for 15 minutes before planting.', 'Treat setts with Trichoderma viride or Pseudomonas fluorescens.', 'https://images.unsplash.com/photo-1598112972019-91e1162b80f7?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Maize', 'Fall Armyworm (Spodoptera frugiperda)', 'Large ragged holes on leaves, sawdust-like frass in the whorls, severe defoliation.', 'Larvae of the Fall Armyworm moth feeding aggressively on whorls.', 'Early planting, intercropping with legumes, installing pheromone traps.', 'Spray Emamectin benzoate 5 SG @ 0.4g/litre or Spinetoram 11.7 SC @ 0.5ml/litre.', 'Whorl application of Neem seed kernel extract (NSKE) 5% or sand mixed with lime.', 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Onion', 'Purple Blotch (Alternaria porri)', 'Small, sunken, whitish flecks with purple centers on leaves, leading to leaf dieback.', 'Fungus favored by warm, humid weather and heavy dew.', 'Proper spacing for ventilation, 3-year crop rotation, wide spacing.', 'Spray Mancozeb 75 WP @ 2.5g/litre or Tebuconazole 25.9 EC @ 1ml/litre.', 'Spray Panchagavya 3% or Neem oil 5ml/litre at initial stages.', 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=600&auto=format&fit=crop&q=80', 'Rabi'),
('Chilli', 'Fruit Rot / Anthracnose', 'Sunken, dark circular spots on ripe fruits, pinkish spore masses in humid weather.', 'Fungus Colletotrichum capsici.', 'Use disease-free seeds, proper drainage, avoid overhead irrigation.', 'Spray Azoxystrobin 23 SC @ 1ml/litre or Copper Oxychloride 50 WP @ 2.5g/litre.', 'Seed treatment with Trichoderma viride @ 10g/kg; spray sour buttermilk.', 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Groundnut', 'Tikka Disease (Leaf Spot)', 'Dark brown circular spots with yellow halos on older leaves causing defoliation.', 'Fungus Cercospora arachidicola favored by high humidity.', 'Crop rotation, early sowing, destroying plant debris.', 'Spray Chlorothalonil 75 WP @ 2g/litre or Hexaconazole 5 EC @ 1ml/litre.', 'Spray 5% NSKE (Neem Seed Kernel Extract) or Pseudomonas fluorescens.', 'https://images.unsplash.com/photo-1567306301408-9b74779a11af?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Banana', 'Panama Wilt (Fusarium oxysporum)', 'Yellowing of older outer leaves starting from leaf margins, internal browning of pseudostem when cut.', 'Soil-borne fungus Fusarium oxysporum f.sp. cubense, persists in soil for decades.', 'Plant resistant varieties (Grand Naine, Robusta), avoid replanting in infected soil.', 'Drench soil with Carbendazim 50 WP @ 1g/litre around the base.', 'Soil drench with Pseudomonas fluorescens @ 2.5 kg/acre + Trichoderma harzianum @ 2.5 kg/acre.', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Banana', 'Sigatoka Leaf Spot (Mycosphaerella musicola)', 'Pale yellow streaks on young leaves, turning brown-black oval spots with yellow halo; premature leaf death.', 'Fungus Mycosphaerella musicola, spreads by wind and rain splash in humid weather.', 'Remove and destroy infected leaves, maintain proper spacing for airflow.', 'Spray Propiconazole 25 EC @ 1ml/litre or Mancozeb 75 WP @ 2.5g/litre at 3-week intervals.', 'Spray Bordeaux mixture (1%) or Neem oil 5ml/litre every 15 days.', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Mango', 'Powdery Mildew (Oidium mangiferae)', 'White powdery coating on young leaves, flowers, and fruitlets. Flower drop leads to low fruit set.', 'Fungus Oidium mangiferae, favored by dry weather with high humidity at night.', 'Plant resistant varieties, ensure proper pruning for air circulation, avoid dense canopy.', 'Spray Carbendazim 50 WP @ 1g/litre or Wettable Sulphur 80 WP @ 2g/litre at bud burst.', 'Spray 5% Neem seed kernel extract (NSKE) or dilute neem oil (3ml/litre) before bud break.', 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80', 'Rabi'),
('Mango', 'Mango Hopper (Idioscopus clypealis)', 'Nymphs and adults suck sap from tender shoots, flowers curl, dry up and drop. Sticky honeydew causes sooty mold.', 'Mango leaf hopper insects thriving during flowering season.', 'Prune dense shoots before season, avoid excess nitrogen which promotes tender growth.', 'Spray Imidacloprid 17.8 SL @ 0.3ml/litre or Thiamethoxam 25 WG @ 0.3g/litre.', 'Spray Neem oil 5ml/litre + liquid soap 2ml/litre. Release natural predators like Chrysoperla larvae.', 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?w=600&auto=format&fit=crop&q=80', 'Rabi'),
('Coconut', 'Root Wilt Disease', 'Yellowing and drooping of lower fronds, spindle leaves appear bunched, button shedding, premature nut fall.', 'Phytoplasma organism transmitted by mealybug Myndus crudus.', 'Grow resistant varieties, maintain tree nutrition, manage vector insects.', 'Inject Oxytetracycline HCl (25g/tree) into the trunk every 6 months.', 'Apply 50 kg well-decomposed FYM per palm + irrigation during summer; spray Neem oil on crown.', 'https://images.unsplash.com/photo-1627308595229-7830a5c18037?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Brinjal', 'Shoot and Fruit Borer (Leucinodes orbonalis)', 'Wilting of young shoots (dead heart), larvae bore into fruits causing rotting, pin holes on fruits.', 'Leucinodes orbonalis larvae boring into tender shoots and fruits.', 'Install pheromone traps (5/acre), collect and destroy infested shoots and fruits.', 'Spray Spinosad 45 SC @ 0.3ml/litre or Chlorantraniliprole 18.5 SC @ 0.3ml/litre.', 'Release egg parasitoid Trichogramma chilonis @ 50,000/acre; spray Bt (Bacillus thuringiensis) @ 2g/litre.', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Potato', 'Late Blight (Phytophthora infestans)', 'Water-soaked, irregular grey-green spots on leaves and stems turning brown-black; white fluffy growth on underside.', 'Oomycete Phytophthora infestans, spreads rapidly in cool, humid conditions.', 'Use certified seed tubers, avoid overhead irrigation, maintain proper plant spacing.', 'Spray Metalaxyl + Mancozeb 72 WP @ 2.5g/litre or Cymoxanil 8% + Mancozeb 64% WP @ 3g/litre.', 'Spray Copper Oxychloride 50 WP @ 3g/litre or Bordeaux mixture 1% as preventive spray.', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80', 'Rabi'),
('Soybean', 'Yellow Mosaic Disease', 'Bright yellow-green mosaic patches on leaves, pods fail to develop, plants stunted.', 'Mungbean Yellow Mosaic Virus (MYMV) transmitted by whitefly Bemisia tabaci.', 'Use resistant varieties (MACS 450, Phule Agrani), install yellow sticky traps.', 'No direct cure. Control the whitefly vector: Spray Thiamethoxam 25 WG @ 0.3g/litre.', 'Remove and destroy infected plants immediately; spray Neem oil 5ml/litre to control whitefly.', 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Cucumber', 'Downy Mildew (Pseudoperonospora cubensis)', 'Angular, yellow water-soaked patches between veins on upper leaf surface; grey-purple mold growth on lower side.', 'Pseudoperonospora cubensis, spreads through wind and rain splash in cool, moist weather.', 'Use resistant varieties, drip irrigation instead of overhead, remove infected leaves.', 'Spray Metalaxyl + Mancozeb 72 WP @ 2.5g/litre or Dimethomorph 50 WP @ 1g/litre.', 'Spray Copper Oxychloride 3g/litre or diluted milk solution (1:9 milk to water) as a preventive.', 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Tomato', 'Early Blight (Alternaria solani)', 'Dark brown concentric ring target-board spots on older leaves; lesions enlarge and cause defoliation.', 'Fungus Alternaria solani favored by warm temperatures (24-29°C) and leaf wetness.', 'Crop rotation, use certified seeds, remove crop debris, stake plants for airflow.', 'Spray Chlorothalonil 75 WP @ 2g/litre or Azoxystrobin 23 SC @ 1ml/litre.', 'Spray Trichoderma viride @ 5g/litre or Copper Oxychloride 3g/litre every 10-14 days.', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80', 'All Season'),
('Cotton', 'Alternaria Leaf Spot', 'Circular brown spots with concentric rings on leaves, spots dry up and fall leaving shot-hole appearance.', 'Fungus Alternaria macrospora, severe in warm and humid conditions.', 'Crop rotation, seed treatment, remove infected debris promptly.', 'Spray Mancozeb 75 WP @ 2.5g/litre or Iprodione 50 WP @ 1.5g/litre.', 'Spray Neem leaf extract (5%) or Pseudomonas fluorescens @ 2.5g/litre.', 'https://images.unsplash.com/photo-1628172908865-c70e28f28ab5?w=600&auto=format&fit=crop&q=80', 'Kharif'),
('Paddy', 'Brown Planthopper (Nilaparvata lugens)', 'Circular scorched hopper burn patches, plants dry up and collapse; muddy odor from infested fields.', 'Nilaparvata lugens nymphs and adults sucking phloem sap at plant base.', 'Plant resistant varieties (IR 36, IR 64), reduce nitrogen application, drain field water.', 'Spray Buprofezin 25 SC @ 1ml/litre or Pymetrozine 50 WG @ 0.3g/litre.', 'Spray Neem oil 5ml/litre near plant base; install light traps to monitor pest pressure.', 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=600&auto=format&fit=crop&q=80', 'Kharif')
ON CONFLICT DO NOTHING;
